// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package database

import (
	"context"
)

// iteratorForCreateMailQueueItems implements pgx.CopyFromSource.
type iteratorForCreateMailQueueItems struct {
	rows                 []CreateMailQueueItemsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateMailQueueItems) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateMailQueueItems) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].TaskID,
		r.rows[0].RecipientFullName,
		r.rows[0].RecipientEmail,
		r.rows[0].Subject,
		r.rows[0].Body,
		r.rows[0].BodyHtml,
	}, nil
}

func (r iteratorForCreateMailQueueItems) Err() error {
	return nil
}

func (q *Queries) CreateMailQueueItems(ctx context.Context, arg []CreateMailQueueItemsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"mail_queue"}, []string{"task_id", "recipient_full_name", "recipient_email", "subject", "body", "body_html"}, &iteratorForCreateMailQueueItems{rows: arg})
}
