// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type MailingList struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type MailingListRecipient struct {
	MailListID  uuid.UUID `json:"mail_list_id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

type Recipient struct {
	ID        uuid.UUID `json:"id"`
	FullName  string    `json:"full_name"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Template struct {
	ID                uuid.UUID `json:"id"`
	Name              string    `json:"name"`
	HtmlContent       string    `json:"html_content"`
	PlainTextContent  string    `json:"plain_text_content"`
	ReactEmailContent string    `json:"react_email_content"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}
