// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type AuthoringMode string

const (
	AuthoringModeJsx    AuthoringMode = "jsx"
	AuthoringModeVisual AuthoringMode = "visual"
	AuthoringModeHtml   AuthoringMode = "html"
)

func (e *AuthoringMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthoringMode(s)
	case string:
		*e = AuthoringMode(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthoringMode: %T", src)
	}
	return nil
}

type NullAuthoringMode struct {
	AuthoringMode AuthoringMode `json:"authoring_mode"`
	Valid         bool          `json:"valid"` // Valid is true if AuthoringMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthoringMode) Scan(value interface{}) error {
	if value == nil {
		ns.AuthoringMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthoringMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthoringMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthoringMode), nil
}

type MailQueueStatus string

const (
	MailQueueStatusPending    MailQueueStatus = "pending"
	MailQueueStatusProcessing MailQueueStatus = "processing"
	MailQueueStatusSent       MailQueueStatus = "sent"
	MailQueueStatusFailed     MailQueueStatus = "failed"
)

func (e *MailQueueStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MailQueueStatus(s)
	case string:
		*e = MailQueueStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MailQueueStatus: %T", src)
	}
	return nil
}

type NullMailQueueStatus struct {
	MailQueueStatus MailQueueStatus `json:"mail_queue_status"`
	Valid           bool            `json:"valid"` // Valid is true if MailQueueStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMailQueueStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MailQueueStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MailQueueStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMailQueueStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MailQueueStatus), nil
}

type TemplateAuthorKind string

const (
	TemplateAuthorKindOperator     TemplateAuthorKind = "operator"
	TemplateAuthorKindTemplateSeed TemplateAuthorKind = "template_seed"
)

func (e *TemplateAuthorKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TemplateAuthorKind(s)
	case string:
		*e = TemplateAuthorKind(s)
	default:
		return fmt.Errorf("unsupported scan type for TemplateAuthorKind: %T", src)
	}
	return nil
}

type NullTemplateAuthorKind struct {
	TemplateAuthorKind TemplateAuthorKind `json:"template_author_kind"`
	Valid              bool               `json:"valid"` // Valid is true if TemplateAuthorKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTemplateAuthorKind) Scan(value interface{}) error {
	if value == nil {
		ns.TemplateAuthorKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TemplateAuthorKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTemplateAuthorKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TemplateAuthorKind), nil
}

type MailQueue struct {
	ID                uuid.UUID           `json:"id"`
	TaskID            uuid.UUID           `json:"task_id"`
	RecipientFullName string              `json:"recipient_full_name"`
	RecipientEmail    string              `json:"recipient_email"`
	Subject           string              `json:"subject"`
	Body              string              `json:"body"`
	BodyHtml          *string             `json:"body_html"`
	Status            NullMailQueueStatus `json:"status"`
	Error             *string             `json:"error"`
	CreatedAt         *time.Time          `json:"created_at"`
	Attempts          int                 `json:"attempts"`
	NextAttemptAt     time.Time           `json:"next_attempt_at"`
}

type MailTask struct {
	ID            uuid.UUID  `json:"id"`
	SentBy        string     `json:"sent_by"`
	TemplateID    *uuid.UUID `json:"template_id"`
	MailListID    *uuid.UUID `json:"mail_list_id"`
	BodyVariables []byte     `json:"body_variables"`
	CreatedAt     time.Time  `json:"created_at"`
}

type MailingList struct {
	ID          uuid.UUID  `json:"id"`
	Name        string     `json:"name"`
	Description *string    `json:"description"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ArchivedAt  *time.Time `json:"archived_at"`
	ArchivedBy  *string    `json:"archived_by"`
}

type MailingListRecipient struct {
	MailListID  uuid.UUID `json:"mail_list_id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

type Recipient struct {
	ID        uuid.UUID `json:"id"`
	FullName  string    `json:"full_name"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Template struct {
	ID                 uuid.UUID  `json:"id"`
	Name               string     `json:"name"`
	HtmlContent        string     `json:"html_content"`
	PlainTextContent   string     `json:"plain_text_content"`
	ReactEmailContent  string     `json:"react_email_content"`
	CreatedAt          time.Time  `json:"created_at"`
	UpdatedAt          time.Time  `json:"updated_at"`
	Subject            string     `json:"subject"`
	ArchivedAt         *time.Time `json:"archived_at"`
	ArchivedBy         *string    `json:"archived_by"`
	Key                *string    `json:"key"`
	System             bool       `json:"system"`
	PublishedVersionID *uuid.UUID `json:"published_version_id"`
	// Required variables from the sending service's contract, sorted by name, each with why the mail needs it. Written only by the Template seed; locked in the panel.
	ContractRequiredVariables ContractVariables `json:"contract_required_variables"`
	// Required variables operators marked, sorted. Never shares a name with contract_required_variables.
	OperatorRequiredVariables []string   `json:"operator_required_variables"`
	SeedRefusedAt             *time.Time `json:"-"`
	SeedRefusedRules          []string   `json:"-"`
	SeedRefusedPayloadSha256  *string    `json:"-"`
}

type TemplateVersion struct {
	ID               uuid.UUID          `json:"id"`
	TemplateID       uuid.UUID          `json:"template_id"`
	Seq              int                `json:"seq"`
	Subject          string             `json:"subject"`
	RequestedSubject *string            `json:"requested_subject"`
	JsxSource        *string            `json:"jsx_source"`
	VisualSource     []byte             `json:"visual_source"`
	HtmlSource       *string            `json:"html_source"`
	MainMode         AuthoringMode      `json:"main_mode"`
	HtmlContent      string             `json:"html_content"`
	PlainTextContent string             `json:"plain_text_content"`
	AuthorKind       TemplateAuthorKind `json:"author_kind"`
	AuthorSub        *string            `json:"author_sub"`
	AuthorName       *string            `json:"author_name"`
	CreatedAt        time.Time          `json:"created_at"`
	PublishedAt      *time.Time         `json:"published_at"`
	BaseVersionID    *uuid.UUID         `json:"base_version_id"`
	DiscardedAt      *time.Time         `json:"discarded_at"`
}

type TemplateVersionSummary struct {
	ID               uuid.UUID          `json:"id"`
	TemplateID       uuid.UUID          `json:"template_id"`
	Seq              int                `json:"seq"`
	Subject          string             `json:"subject"`
	RequestedSubject *string            `json:"requested_subject"`
	MainMode         AuthoringMode      `json:"main_mode"`
	AuthorKind       TemplateAuthorKind `json:"author_kind"`
	AuthorSub        *string            `json:"author_sub"`
	AuthorName       *string            `json:"author_name"`
	CreatedAt        time.Time          `json:"created_at"`
	PublishedAt      *time.Time         `json:"published_at"`
	BaseVersionID    *uuid.UUID         `json:"base_version_id"`
	IsCurrent        bool               `json:"is_current"`
	DiscardedAt      *time.Time         `json:"discarded_at"`
}
