// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addOperatorRequiredVariable = `-- name: AddOperatorRequiredVariable :one
UPDATE templates
SET operator_required_variables = CASE
                                      WHEN $1::text = ANY (contract_variable_names(contract_required_variables))
                                          THEN operator_required_variables
                                      ELSE ARRAY(SELECT DISTINCT n COLLATE "C"
                                                 FROM unnest(array_append(operator_required_variables, $1::text)) AS n
                                                 ORDER BY n COLLATE "C")
    END
WHERE id = $2
  AND archived_at IS NULL
RETURNING id, name, html_content, plain_text_content, react_email_content, created_at, updated_at, subject, archived_at, archived_by, key, system, published_version_id, contract_required_variables, operator_required_variables
`

type AddOperatorRequiredVariableParams struct {
	Name string    `json:"name"`
	ID   uuid.UUID `json:"id"`
}

// Required variable sets are sorted byte by byte (COLLATE "C"), the order the
// handler sorts a contract set in and a missing list comes in, whatever the
// database's collation.
//
// Marks a variable of a template in use as required by operators. A name
// already in either set changes nothing: one the contract declares is required
// already, and stays the contract's. Takes the row's lock, so the caller can
// check the body against the sets it returns before committing.
func (q *Queries) AddOperatorRequiredVariable(ctx context.Context, arg AddOperatorRequiredVariableParams) (Template, error) {
	row := q.db.QueryRow(ctx, addOperatorRequiredVariable, arg.Name, arg.ID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HtmlContent,
		&i.PlainTextContent,
		&i.ReactEmailContent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subject,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.Key,
		&i.System,
		&i.PublishedVersionID,
		&i.ContractRequiredVariables,
		&i.OperatorRequiredVariables,
	)
	return i, err
}

const addRecipientToMailingList = `-- name: AddRecipientToMailingList :one
WITH target_list AS (
    SELECT mailing_lists.id
    FROM mailing_lists
    WHERE mailing_lists.id = $1
      AND archived_at IS NULL
), recipient AS (
    INSERT INTO recipients (full_name, email)
        SELECT $2, $3 FROM target_list
        ON CONFLICT (email) DO UPDATE SET full_name = EXCLUDED.full_name
        RETURNING id, full_name, email, created_at, updated_at),
     association AS (
         INSERT INTO mailing_list_recipients (mail_list_id, recipient_id)
             SELECT $1, id FROM recipient
             ON CONFLICT DO NOTHING)
SELECT id, full_name, email, created_at, updated_at
FROM recipient
`

type AddRecipientToMailingListParams struct {
	MailListID uuid.UUID `json:"mail_list_id"`
	FullName   string    `json:"full_name"`
	Email      string    `json:"email"`
}

type AddRecipientToMailingListRow struct {
	ID        uuid.UUID `json:"id"`
	FullName  string    `json:"full_name"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) AddRecipientToMailingList(ctx context.Context, arg AddRecipientToMailingListParams) (AddRecipientToMailingListRow, error) {
	row := q.db.QueryRow(ctx, addRecipientToMailingList, arg.MailListID, arg.FullName, arg.Email)
	var i AddRecipientToMailingListRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const archiveMailingList = `-- name: ArchiveMailingList :one
UPDATE mailing_lists
SET archived_by = CASE
                      WHEN archived_at IS NULL THEN $1::text
                      ELSE archived_by
                  END,
    archived_at = COALESCE(archived_at, NOW()),
    updated_at = CASE WHEN archived_at IS NULL THEN NOW() ELSE updated_at END
WHERE id = $2
RETURNING id, name, description, created_at, updated_at, archived_at, archived_by
`

type ArchiveMailingListParams struct {
	ArchivedBy *string   `json:"archived_by"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) ArchiveMailingList(ctx context.Context, arg ArchiveMailingListParams) (MailingList, error) {
	row := q.db.QueryRow(ctx, archiveMailingList, arg.ArchivedBy, arg.ID)
	var i MailingList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.ArchivedBy,
	)
	return i, err
}

const archiveTemplate = `-- name: ArchiveTemplate :one
UPDATE templates
SET archived_by = CASE
                      WHEN archived_at IS NULL THEN $1::text
                      ELSE archived_by
                  END,
    archived_at = COALESCE(archived_at, NOW()),
    updated_at = CASE WHEN archived_at IS NULL THEN NOW() ELSE updated_at END
WHERE id = $2
  AND system = false
RETURNING id, name, html_content, plain_text_content, react_email_content, created_at, updated_at, subject, archived_at, archived_by, key, system, published_version_id, contract_required_variables, operator_required_variables
`

type ArchiveTemplateParams struct {
	ArchivedBy *string   `json:"archived_by"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) ArchiveTemplate(ctx context.Context, arg ArchiveTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, archiveTemplate, arg.ArchivedBy, arg.ID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HtmlContent,
		&i.PlainTextContent,
		&i.ReactEmailContent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subject,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.Key,
		&i.System,
		&i.PublishedVersionID,
		&i.ContractRequiredVariables,
		&i.OperatorRequiredVariables,
	)
	return i, err
}

const countAllMailingListsIncludingArchived = `-- name: CountAllMailingListsIncludingArchived :one
SELECT count(*)
FROM mailing_lists
`

func (q *Queries) CountAllMailingListsIncludingArchived(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllMailingListsIncludingArchived)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllTemplatesIncludingArchived = `-- name: CountAllTemplatesIncludingArchived :one
SELECT count(*)
FROM templates
`

func (q *Queries) CountAllTemplatesIncludingArchived(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllTemplatesIncludingArchived)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countArchivedMailingLists = `-- name: CountArchivedMailingLists :one
SELECT count(*)
FROM mailing_lists
WHERE archived_at IS NOT NULL
`

func (q *Queries) CountArchivedMailingLists(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countArchivedMailingLists)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countArchivedTemplates = `-- name: CountArchivedTemplates :one
SELECT count(*)
FROM templates
WHERE archived_at IS NOT NULL
`

func (q *Queries) CountArchivedTemplates(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countArchivedTemplates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMailQueueByStatus = `-- name: CountMailQueueByStatus :one
SELECT (SELECT count(*) FROM mail_queue WHERE status = 'pending')    AS pending,
       (SELECT count(*) FROM mail_queue WHERE status = 'processing') AS processing,
       (SELECT count(*) FROM mail_queue WHERE status = 'sent')       AS sent,
       (SELECT count(*) FROM mail_queue WHERE status = 'failed')     AS failed
`

type CountMailQueueByStatusRow struct {
	Pending    int64 `json:"pending"`
	Processing int64 `json:"processing"`
	Sent       int64 `json:"sent"`
	Failed     int64 `json:"failed"`
}

func (q *Queries) CountMailQueueByStatus(ctx context.Context) (CountMailQueueByStatusRow, error) {
	row := q.db.QueryRow(ctx, countMailQueueByStatus)
	var i CountMailQueueByStatusRow
	err := row.Scan(
		&i.Pending,
		&i.Processing,
		&i.Sent,
		&i.Failed,
	)
	return i, err
}

const countMailQueueItemsByTaskId = `-- name: CountMailQueueItemsByTaskId :one
SELECT count(*)
FROM mail_queue
WHERE task_id = $1
  AND ($2::mail_queue_status IS NULL OR status = $2::mail_queue_status)
`

type CountMailQueueItemsByTaskIdParams struct {
	TaskID uuid.UUID           `json:"task_id"`
	Status NullMailQueueStatus `json:"status"`
}

func (q *Queries) CountMailQueueItemsByTaskId(ctx context.Context, arg CountMailQueueItemsByTaskIdParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMailQueueItemsByTaskId, arg.TaskID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMailTaskSends = `-- name: CountMailTaskSends :one
SELECT count(*)
FROM mail_tasks mt
WHERE ($1::text IS NULL OR mail_task_status(mt.id) = $1::text)
`

func (q *Queries) CountMailTaskSends(ctx context.Context, status *string) (int64, error) {
	row := q.db.QueryRow(ctx, countMailTaskSends, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMailTasks = `-- name: CountMailTasks :one
SELECT count(*)
FROM mail_tasks
`

func (q *Queries) CountMailTasks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMailTasks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMailTasksByStatus = `-- name: CountMailTasksByStatus :one
SELECT count(*) FILTER (WHERE s.status = 'failed')  AS failed,
       count(*) FILTER (WHERE s.status = 'sending') AS sending,
       count(*) FILTER (WHERE s.status = 'sent')    AS sent
FROM (SELECT mail_task_status(mt.id) AS status FROM mail_tasks mt) s
`

type CountMailTasksByStatusRow struct {
	Failed  int64 `json:"failed"`
	Sending int64 `json:"sending"`
	Sent    int64 `json:"sent"`
}

// Sends by the status mail_task_status derives, over every send: the same
// numbers CountMailTaskSends gives for each status filter.
func (q *Queries) CountMailTasksByStatus(ctx context.Context) (CountMailTasksByStatusRow, error) {
	row := q.db.QueryRow(ctx, countMailTasksByStatus)
	var i CountMailTasksByStatusRow
	err := row.Scan(&i.Failed, &i.Sending, &i.Sent)
	return i, err
}

const countMailingLists = `-- name: CountMailingLists :one
SELECT count(*)
FROM mailing_lists
WHERE archived_at IS NULL
`

func (q *Queries) CountMailingLists(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMailingLists)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecipients = `-- name: CountRecipients :one
SELECT count(*)
FROM recipients
`

func (q *Queries) CountRecipients(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRecipients)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecipientsByMailingListId = `-- name: CountRecipientsByMailingListId :one
SELECT count(*)
FROM recipients r
         JOIN mailing_list_recipients mlr ON r.id = mlr.recipient_id
         JOIN mailing_lists ml ON ml.id = mlr.mail_list_id
WHERE mlr.mail_list_id = $1
  AND ml.archived_at IS NULL
`

func (q *Queries) CountRecipientsByMailingListId(ctx context.Context, mailListID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRecipientsByMailingListId, mailListID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTemplateVersions = `-- name: CountTemplateVersions :one
SELECT count(*)
FROM template_versions
WHERE template_id = $1
  AND ($2::boolean IS NULL OR (published_at IS NOT NULL) = $2::boolean)
`

type CountTemplateVersionsParams struct {
	TemplateID uuid.UUID `json:"template_id"`
	Published  *bool     `json:"published"`
}

func (q *Queries) CountTemplateVersions(ctx context.Context, arg CountTemplateVersionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTemplateVersions, arg.TemplateID, arg.Published)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTemplates = `-- name: CountTemplates :one
SELECT count(*)
FROM templates
WHERE archived_at IS NULL
`

func (q *Queries) CountTemplates(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTemplates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

type CreateMailQueueItemsParams struct {
	TaskID            uuid.UUID `json:"task_id"`
	RecipientFullName string    `json:"recipient_full_name"`
	RecipientEmail    string    `json:"recipient_email"`
	Subject           string    `json:"subject"`
	Body              string    `json:"body"`
	BodyHtml          *string   `json:"body_html"`
}

const createMailTask = `-- name: CreateMailTask :many
WITH active_source AS (
    SELECT t.id AS template_id, ml.id AS mail_list_id
    FROM templates t
             JOIN mailing_lists ml ON ml.id = $1::uuid
    WHERE t.id = $2::uuid
      AND t.archived_at IS NULL
      AND ml.archived_at IS NULL
), inserted_task AS (
    INSERT INTO mail_tasks (sent_by, template_id, mail_list_id, body_variables)
        SELECT $3, template_id, mail_list_id, $4 FROM active_source
        RETURNING id, sent_by, template_id, mail_list_id, body_variables, created_at
)
SELECT it.id               AS task_id,
       it.body_variables,
       t.name              AS template_name,
       t.subject           AS template_subject,
       t.html_content,
       t.plain_text_content,
       r.full_name         AS recipient_full_name,
       r.email             AS recipient_email
FROM inserted_task it
         JOIN templates t ON it.template_id = t.id
         JOIN mailing_list_recipients mlr ON it.mail_list_id = mlr.mail_list_id
         JOIN recipients r ON mlr.recipient_id = r.id
`

type CreateMailTaskParams struct {
	MailListID    *uuid.UUID `json:"mail_list_id"`
	TemplateID    *uuid.UUID `json:"template_id"`
	SentBy        string     `json:"sent_by"`
	BodyVariables []byte     `json:"body_variables"`
}

type CreateMailTaskRow struct {
	TaskID            uuid.UUID `json:"task_id"`
	BodyVariables     []byte    `json:"body_variables"`
	TemplateName      string    `json:"template_name"`
	TemplateSubject   string    `json:"template_subject"`
	HtmlContent       string    `json:"html_content"`
	PlainTextContent  string    `json:"plain_text_content"`
	RecipientFullName string    `json:"recipient_full_name"`
	RecipientEmail    string    `json:"recipient_email"`
}

func (q *Queries) CreateMailTask(ctx context.Context, arg CreateMailTaskParams) ([]CreateMailTaskRow, error) {
	rows, err := q.db.Query(ctx, createMailTask,
		arg.MailListID,
		arg.TemplateID,
		arg.SentBy,
		arg.BodyVariables,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreateMailTaskRow
	for rows.Next() {
		var i CreateMailTaskRow
		if err := rows.Scan(
			&i.TaskID,
			&i.BodyVariables,
			&i.TemplateName,
			&i.TemplateSubject,
			&i.HtmlContent,
			&i.PlainTextContent,
			&i.RecipientFullName,
			&i.RecipientEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createMailingList = `-- name: CreateMailingList :one
INSERT INTO mailing_lists (name)
VALUES ($1)
RETURNING id, name, description, created_at, updated_at, archived_at, archived_by
`

func (q *Queries) CreateMailingList(ctx context.Context, name string) (MailingList, error) {
	row := q.db.QueryRow(ctx, createMailingList, name)
	var i MailingList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.ArchivedBy,
	)
	return i, err
}

const createSingleMailTask = `-- name: CreateSingleMailTask :one
WITH active_template AS (
    SELECT templates.id
    FROM templates
    WHERE templates.id = $3::uuid
      AND archived_at IS NULL
), inserted_task AS (
    INSERT INTO mail_tasks (sent_by, template_id, body_variables)
        SELECT $4, id, $5 FROM active_template
        RETURNING id, sent_by, template_id, mail_list_id, body_variables, created_at
)
SELECT it.id               AS task_id,
       it.body_variables,
       t.name              AS template_name,
       t.subject           AS template_subject,
       t.html_content,
       t.plain_text_content,
       $1::text AS recipient_full_name,
       $2::text AS recipient_email
FROM inserted_task it
         JOIN templates t ON it.template_id = t.id
`

type CreateSingleMailTaskParams struct {
	RecipientFullName string     `json:"recipient_full_name"`
	RecipientEmail    string     `json:"recipient_email"`
	TemplateID        *uuid.UUID `json:"template_id"`
	SentBy            string     `json:"sent_by"`
	BodyVariables     []byte     `json:"body_variables"`
}

type CreateSingleMailTaskRow struct {
	TaskID            uuid.UUID `json:"task_id"`
	BodyVariables     []byte    `json:"body_variables"`
	TemplateName      string    `json:"template_name"`
	TemplateSubject   string    `json:"template_subject"`
	HtmlContent       string    `json:"html_content"`
	PlainTextContent  string    `json:"plain_text_content"`
	RecipientFullName string    `json:"recipient_full_name"`
	RecipientEmail    string    `json:"recipient_email"`
}

func (q *Queries) CreateSingleMailTask(ctx context.Context, arg CreateSingleMailTaskParams) (CreateSingleMailTaskRow, error) {
	row := q.db.QueryRow(ctx, createSingleMailTask,
		arg.RecipientFullName,
		arg.RecipientEmail,
		arg.TemplateID,
		arg.SentBy,
		arg.BodyVariables,
	)
	var i CreateSingleMailTaskRow
	err := row.Scan(
		&i.TaskID,
		&i.BodyVariables,
		&i.TemplateName,
		&i.TemplateSubject,
		&i.HtmlContent,
		&i.PlainTextContent,
		&i.RecipientFullName,
		&i.RecipientEmail,
	)
	return i, err
}

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (name, subject, html_content, plain_text_content, react_email_content, key)
VALUES ($1, $2, $3, $4, $5, $6::text)
RETURNING id, name, html_content, plain_text_content, react_email_content, created_at, updated_at, subject, archived_at, archived_by, key, system, published_version_id, contract_required_variables, operator_required_variables
`

type CreateTemplateParams struct {
	Name              string  `json:"name"`
	Subject           string  `json:"subject"`
	HtmlContent       string  `json:"html_content"`
	PlainTextContent  string  `json:"plain_text_content"`
	ReactEmailContent string  `json:"react_email_content"`
	Key               *string `json:"key"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.Name,
		arg.Subject,
		arg.HtmlContent,
		arg.PlainTextContent,
		arg.ReactEmailContent,
		arg.Key,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HtmlContent,
		&i.PlainTextContent,
		&i.ReactEmailContent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subject,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.Key,
		&i.System,
		&i.PublishedVersionID,
		&i.ContractRequiredVariables,
		&i.OperatorRequiredVariables,
	)
	return i, err
}

const discardTemplateDraft = `-- name: DiscardTemplateDraft :exec
UPDATE template_versions
SET discarded_at = COALESCE(discarded_at, NOW())
WHERE template_id = $1
  AND id = $2
  AND published_at IS NULL
`

type DiscardTemplateDraftParams struct {
	TemplateID uuid.UUID `json:"template_id"`
	ID         uuid.UUID `json:"id"`
}

// Discards a draft: it stays in the history, but it is nobody's draft in
// progress any more and it is never published. A draft discarded already
// keeps the time it was. The caller holds the template row's lock and has
// checked that the version is a draft of this template.
func (q *Queries) DiscardTemplateDraft(ctx context.Context, arg DiscardTemplateDraftParams) error {
	_, err := q.db.Exec(ctx, discardTemplateDraft, arg.TemplateID, arg.ID)
	return err
}

const getAllMailingLists = `-- name: GetAllMailingLists :many
SELECT id, name, description, created_at, updated_at, archived_at, archived_by
FROM mailing_lists
WHERE archived_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllMailingListsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllMailingLists(ctx context.Context, arg GetAllMailingListsParams) ([]MailingList, error) {
	rows, err := q.db.Query(ctx, getAllMailingLists, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MailingList
	for rows.Next() {
		var i MailingList
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.ArchivedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllMailingListsIncludingArchived = `-- name: GetAllMailingListsIncludingArchived :many
SELECT id, name, description, created_at, updated_at, archived_at, archived_by
FROM mailing_lists
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllMailingListsIncludingArchivedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllMailingListsIncludingArchived(ctx context.Context, arg GetAllMailingListsIncludingArchivedParams) ([]MailingList, error) {
	rows, err := q.db.Query(ctx, getAllMailingListsIncludingArchived, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MailingList
	for rows.Next() {
		var i MailingList
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.ArchivedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTemplates = `-- name: GetAllTemplates :many
SELECT id, name, html_content, plain_text_content, react_email_content, created_at, updated_at, subject, archived_at, archived_by, key, system, published_version_id, contract_required_variables, operator_required_variables
FROM templates
WHERE archived_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllTemplatesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllTemplates(ctx context.Context, arg GetAllTemplatesParams) ([]Template, error) {
	rows, err := q.db.Query(ctx, getAllTemplates, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HtmlContent,
			&i.PlainTextContent,
			&i.ReactEmailContent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Subject,
			&i.ArchivedAt,
			&i.ArchivedBy,
			&i.Key,
			&i.System,
			&i.PublishedVersionID,
			&i.ContractRequiredVariables,
			&i.OperatorRequiredVariables,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTemplatesIncludingArchived = `-- name: GetAllTemplatesIncludingArchived :many
SELECT id, name, html_content, plain_text_content, react_email_content, created_at, updated_at, subject, archived_at, archived_by, key, system, published_version_id, contract_required_variables, operator_required_variables
FROM templates
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllTemplatesIncludingArchivedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllTemplatesIncludingArchived(ctx context.Context, arg GetAllTemplatesIncludingArchivedParams) ([]Template, error) {
	rows, err := q.db.Query(ctx, getAllTemplatesIncludingArchived, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HtmlContent,
			&i.PlainTextContent,
			&i.ReactEmailContent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Subject,
			&i.ArchivedAt,
			&i.ArchivedBy,
			&i.Key,
			&i.System,
			&i.PublishedVersionID,
			&i.ContractRequiredVariables,
			&i.OperatorRequiredVariables,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchivedMailingLists = `-- name: GetArchivedMailingLists :many
SELECT id, name, description, created_at, updated_at, archived_at, archived_by
FROM mailing_lists
WHERE archived_at IS NOT NULL
ORDER BY archived_at DESC
LIMIT $1 OFFSET $2
`

type GetArchivedMailingListsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetArchivedMailingLists(ctx context.Context, arg GetArchivedMailingListsParams) ([]MailingList, error) {
	rows, err := q.db.Query(ctx, getArchivedMailingLists, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MailingList
	for rows.Next() {
		var i MailingList
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.ArchivedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchivedTemplates = `-- name: GetArchivedTemplates :many
SELECT id, name, html_content, plain_text_content, react_email_content, created_at, updated_at, subject, archived_at, archived_by, key, system, published_version_id, contract_required_variables, operator_required_variables
FROM templates
WHERE archived_at IS NOT NULL
ORDER BY archived_at DESC
LIMIT $1 OFFSET $2
`

type GetArchivedTemplatesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetArchivedTemplates(ctx context.Context, arg GetArchivedTemplatesParams) ([]Template, error) {
	rows, err := q.db.Query(ctx, getArchivedTemplates, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HtmlContent,
			&i.PlainTextContent,
			&i.ReactEmailContent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Subject,
			&i.ArchivedAt,
			&i.ArchivedBy,
			&i.Key,
			&i.System,
			&i.PublishedVersionID,
			&i.ContractRequiredVariables,
			&i.OperatorRequiredVariables,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailySentCounts = `-- name: GetDailySentCounts :many
WITH today AS (SELECT ($2::timestamptz AT TIME ZONE $1::text)::date AS day),
     days AS (SELECT today.day - back AS day
              FROM today,
                   generate_series(0, $3::int - 1) AS back)
SELECT d.day::date        AS day,
       count(q.created_at) AS sent
FROM days d
         LEFT JOIN mail_queue q
                   ON q.status = 'sent'
                       AND q.created_at >= (d.day::timestamp AT TIME ZONE $1::text)
                       AND q.created_at < ((d.day + 1)::timestamp AT TIME ZONE $1::text)
GROUP BY d.day
ORDER BY d.day
`

type GetDailySentCountsParams struct {
	TimeZone string    `json:"time_zone"`
	AsOf     time.Time `json:"as_of"`
	Days     int       `json:"days"`
}

type GetDailySentCountsRow struct {
	Day  time.Time `json:"day"`
	Sent int64     `json:"sent"`
}

// A queue row has no sent time of its own. created_at — when that recipient's
// mail was queued — stands in for it: the dispatcher is woken on enqueue, so a
// mail that goes through on its first attempt leaves within seconds, and only a
// retried one (the ladder tops out under eight minutes) can land later.
// next_attempt_at is not used: every row older than the retry migration holds
// that migration's timestamp in it.
// Days are calendar days in time_zone; the series ends on as_of's day and has
// one row per day, zero-filled.
func (q *Queries) GetDailySentCounts(ctx context.Context, arg GetDailySentCountsParams) ([]GetDailySentCountsRow, error) {
	rows, err := q.db.Query(ctx, getDailySentCounts, arg.TimeZone, arg.AsOf, arg.Days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailySentCountsRow
	for rows.Next() {
		var i GetDailySentCountsRow
		if err := rows.Scan(&i.Day, &i.Sent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMailQueueItemsByTaskId = `-- name: GetMailQueueItemsByTaskId :many
SELECT id, recipient_full_name, recipient_email, status, error, attempts, next_attempt_at, created_at
FROM mail_queue
WHERE task_id = $1
  AND ($4::mail_queue_status IS NULL OR status = $4::mail_queue_status)
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type GetMailQueueItemsByTaskIdParams struct {
	TaskID uuid.UUID           `json:"task_id"`
	Limit  int32               `json:"limit"`
	Offset int32               `json:"offset"`
	Status NullMailQueueStatus `json:"status"`
}

type GetMailQueueItemsByTaskIdRow struct {
	ID                uuid.UUID           `json:"id"`
	RecipientFullName string              `json:"recipient_full_name"`
	RecipientEmail    string              `json:"recipient_email"`
	Status            NullMailQueueStatus `json:"status"`
	Error             *string             `json:"error"`
	Attempts          int                 `json:"attempts"`
	NextAttemptAt     time.Time           `json:"next_attempt_at"`
	CreatedAt         *time.Time          `json:"created_at"`
}

// A send's recipients, newest first. A list send's rows come from one insert
// and share a created_at, so the id breaks the tie: pages neither repeat nor
// skip a recipient. A NULL status lists every recipient.
func (q *Queries) GetMailQueueItemsByTaskId(ctx context.Context, arg GetMailQueueItemsByTaskIdParams) ([]GetMailQueueItemsByTaskIdRow, error) {
	rows, err := q.db.Query(ctx, getMailQueueItemsByTaskId,
		arg.TaskID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMailQueueItemsByTaskIdRow
	for rows.Next() {
		var i GetMailQueueItemsByTaskIdRow
		if err := rows.Scan(
			&i.ID,
			&i.RecipientFullName,
			&i.RecipientEmail,
			&i.Status,
			&i.Error,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMailTaskById = `-- name: GetMailTaskById :one
SELECT mt.id, mt.sent_by, mt.template_id, mt.mail_list_id, mt.body_variables, mt.created_at,
       t.name  AS template_name,
       ml.name AS mail_list_name
FROM mail_tasks mt
         LEFT JOIN templates t ON mt.template_id = t.id
         LEFT JOIN mailing_lists ml ON mt.mail_list_id = ml.id
WHERE mt.id = $1
`

type GetMailTaskByIdRow struct {
	ID            uuid.UUID  `json:"id"`
	SentBy        string     `json:"sent_by"`
	TemplateID    *uuid.UUID `json:"template_id"`
	MailListID    *uuid.UUID `json:"mail_list_id"`
	BodyVariables []byte     `json:"body_variables"`
	CreatedAt     time.Time  `json:"created_at"`
	TemplateName  *string    `json:"template_name"`
	MailListName  *string    `json:"mail_list_name"`
}

func (q *Queries) GetMailTaskById(ctx context.Context, id uuid.UUID) (GetMailTaskByIdRow, error) {
	row := q.db.QueryRow(ctx, getMailTaskById, id)
	var i GetMailTaskByIdRow
	err := row.Scan(
		&i.ID,
		&i.SentBy,
		&i.TemplateID,
		&i.MailListID,
		&i.BodyVariables,
		&i.CreatedAt,
		&i.TemplateName,
		&i.MailListName,
	)
	return i, err
}

const getMailingListById = `-- name: GetMailingListById :one
SELECT id, name, description, created_at, updated_at, archived_at, archived_by
FROM mailing_lists
WHERE id = $1
  AND archived_at IS NULL
`

func (q *Queries) GetMailingListById(ctx context.Context, id uuid.UUID) (MailingList, error) {
	row := q.db.QueryRow(ctx, getMailingListById, id)
	var i MailingList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.ArchivedBy,
	)
	return i, err
}

const getMailingListByIdIncludingArchived = `-- name: GetMailingListByIdIncludingArchived :one
SELECT id, name, description, created_at, updated_at, archived_at, archived_by
FROM mailing_lists
WHERE id = $1
`

func (q *Queries) GetMailingListByIdIncludingArchived(ctx context.Context, id uuid.UUID) (MailingList, error) {
	row := q.db.QueryRow(ctx, getMailingListByIdIncludingArchived, id)
	var i MailingList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.ArchivedBy,
	)
	return i, err
}

const getRecipientByEmail = `-- name: GetRecipientByEmail :one
SELECT id, full_name, email, created_at, updated_at
FROM recipients
WHERE email = $1
`

func (q *Queries) GetRecipientByEmail(ctx context.Context, email string) (Recipient, error) {
	row := q.db.QueryRow(ctx, getRecipientByEmail, email)
	var i Recipient
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecipients = `-- name: GetRecipients :many
SELECT id, full_name, email, created_at, updated_at
FROM recipients
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetRecipientsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetRecipients(ctx context.Context, arg GetRecipientsParams) ([]Recipient, error) {
	rows, err := q.db.Query(ctx, getRecipients, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipient
	for rows.Next() {
		var i Recipient
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecipientsByMailingListId = `-- name: GetRecipientsByMailingListId :many
SELECT r.id, r.full_name, r.email, r.created_at, r.updated_at
FROM recipients r
         JOIN mailing_list_recipients mlr ON r.id = mlr.recipient_id
         JOIN mailing_lists ml ON ml.id = mlr.mail_list_id
WHERE mlr.mail_list_id = $1
  AND ml.archived_at IS NULL
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type GetRecipientsByMailingListIdParams struct {
	MailListID uuid.UUID `json:"mail_list_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) GetRecipientsByMailingListId(ctx context.Context, arg GetRecipientsByMailingListIdParams) ([]Recipient, error) {
	rows, err := q.db.Query(ctx, getRecipientsByMailingListId, arg.MailListID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipient
	for rows.Next() {
		var i Recipient
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTemplateById = `-- name: GetTemplateById :one
SELECT id, name, html_content, plain_text_content, react_email_content, created_at, updated_at, subject, archived_at, archived_by, key, system, published_version_id, contract_required_variables, operator_required_variables
FROM templates
WHERE id = $1
  AND archived_at IS NULL
`

func (q *Queries) GetTemplateById(ctx context.Context, id uuid.UUID) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateById, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HtmlContent,
		&i.PlainTextContent,
		&i.ReactEmailContent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subject,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.Key,
		&i.System,
		&i.PublishedVersionID,
		&i.ContractRequiredVariables,
		&i.OperatorRequiredVariables,
	)
	return i, err
}

const getTemplateByIdIncludingArchived = `-- name: GetTemplateByIdIncludingArchived :one
SELECT id, name, html_content, plain_text_content, react_email_content, created_at, updated_at, subject, archived_at, archived_by, key, system, published_version_id, contract_required_variables, operator_required_variables
FROM templates
WHERE id = $1
`

func (q *Queries) GetTemplateByIdIncludingArchived(ctx context.Context, id uuid.UUID) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByIdIncludingArchived, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HtmlContent,
		&i.PlainTextContent,
		&i.ReactEmailContent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subject,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.Key,
		&i.System,
		&i.PublishedVersionID,
		&i.ContractRequiredVariables,
		&i.OperatorRequiredVariables,
	)
	return i, err
}

const getTemplateByKey = `-- name: GetTemplateByKey :one
SELECT id, name, html_content, plain_text_content, react_email_content, created_at, updated_at, subject, archived_at, archived_by, key, system, published_version_id, contract_required_variables, operator_required_variables
FROM templates
WHERE key = $1
  AND archived_at IS NULL
`

func (q *Queries) GetTemplateByKey(ctx context.Context, key *string) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByKey, key)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HtmlContent,
		&i.PlainTextContent,
		&i.ReactEmailContent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subject,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.Key,
		&i.System,
		&i.PublishedVersionID,
		&i.ContractRequiredVariables,
		&i.OperatorRequiredVariables,
	)
	return i, err
}

const getTemplateVersion = `-- name: GetTemplateVersion :one
SELECT s.id, s.template_id, s.seq, s.subject, s.requested_subject, s.main_mode, s.author_kind, s.author_sub, s.author_name, s.created_at, s.published_at, s.base_version_id, s.is_current, s.discarded_at,
       v.jsx_source,
       v.visual_source,
       v.html_source,
       v.html_content,
       v.plain_text_content
FROM template_version_summaries s
         JOIN template_versions v ON v.id = s.id
WHERE s.template_id = $1
  AND s.id = $2
`

type GetTemplateVersionParams struct {
	TemplateID uuid.UUID `json:"template_id"`
	ID         uuid.UUID `json:"id"`
}

type GetTemplateVersionRow struct {
	TemplateVersionSummary TemplateVersionSummary `json:"template_version_summary"`
	JsxSource              *string                `json:"jsx_source"`
	VisualSource           []byte                 `json:"visual_source"`
	HtmlSource             *string                `json:"html_source"`
	HtmlContent            string                 `json:"html_content"`
	PlainTextContent       string                 `json:"plain_text_content"`
}

// One version of one template, whole. A version of another template is not
// found here.
func (q *Queries) GetTemplateVersion(ctx context.Context, arg GetTemplateVersionParams) (GetTemplateVersionRow, error) {
	row := q.db.QueryRow(ctx, getTemplateVersion, arg.TemplateID, arg.ID)
	var i GetTemplateVersionRow
	err := row.Scan(
		&i.TemplateVersionSummary.ID,
		&i.TemplateVersionSummary.TemplateID,
		&i.TemplateVersionSummary.Seq,
		&i.TemplateVersionSummary.Subject,
		&i.TemplateVersionSummary.RequestedSubject,
		&i.TemplateVersionSummary.MainMode,
		&i.TemplateVersionSummary.AuthorKind,
		&i.TemplateVersionSummary.AuthorSub,
		&i.TemplateVersionSummary.AuthorName,
		&i.TemplateVersionSummary.CreatedAt,
		&i.TemplateVersionSummary.PublishedAt,
		&i.TemplateVersionSummary.BaseVersionID,
		&i.TemplateVersionSummary.IsCurrent,
		&i.TemplateVersionSummary.DiscardedAt,
		&i.JsxSource,
		&i.VisualSource,
		&i.HtmlSource,
		&i.HtmlContent,
		&i.PlainTextContent,
	)
	return i, err
}

const insertMailTask = `-- name: InsertMailTask :one
INSERT INTO mail_tasks (sent_by, template_id, mail_list_id, body_variables)
SELECT $1, $2, $3, $4
FROM templates
WHERE templates.id = $2
  AND archived_at IS NULL
RETURNING mail_tasks.id, sent_by, template_id, mail_list_id, body_variables, created_at
`

type InsertMailTaskParams struct {
	SentBy        string     `json:"sent_by"`
	TemplateID    *uuid.UUID `json:"template_id"`
	MailListID    *uuid.UUID `json:"mail_list_id"`
	BodyVariables []byte     `json:"body_variables"`
}

func (q *Queries) InsertMailTask(ctx context.Context, arg InsertMailTaskParams) (MailTask, error) {
	row := q.db.QueryRow(ctx, insertMailTask,
		arg.SentBy,
		arg.TemplateID,
		arg.MailListID,
		arg.BodyVariables,
	)
	var i MailTask
	err := row.Scan(
		&i.ID,
		&i.SentBy,
		&i.TemplateID,
		&i.MailListID,
		&i.BodyVariables,
		&i.CreatedAt,
	)
	return i, err
}

const isJSXSource = `-- name: IsJSXSource :one
SELECT (template_jsx_source($1::text) IS NOT NULL)::boolean AS is_source
`

// Whether text is a JSX source by the rule the migration and the old panel's
// writes read react_email_content with: something other than whitespace and
// comments is left in it.
func (q *Queries) IsJSXSource(ctx context.Context, content string) (bool, error) {
	row := q.db.QueryRow(ctx, isJSXSource, content)
	var is_source bool
	err := row.Scan(&is_source)
	return is_source, err
}

const listMailTaskSends = `-- name: ListMailTaskSends :many
WITH page AS (SELECT mt.id
              FROM mail_tasks mt
              WHERE ($3::uuid IS NULL OR mt.id = $3::uuid)
                AND ($4::text IS NULL OR mail_task_status(mt.id) = $4::text)
              ORDER BY mt.created_at DESC, mt.id DESC
              LIMIT $1 OFFSET $2)
SELECT mt.id,
       mt.sent_by,
       mt.template_id,
       mt.mail_list_id,
       mt.body_variables,
       mt.created_at,
       t.name                       AS template_name,
       t.key                        AS template_key,
       ml.name                      AS mail_list_name,
       (ml.id IS NOT NULL)::boolean AS internal_mail_list,
       mail_task_status(mt.id)      AS status,
       rc.pending,
       rc.processing,
       rc.sent,
       rc.failed,
       single.recipient_full_name   AS single_recipient_full_name,
       single.recipient_email       AS single_recipient_email
FROM page
         JOIN mail_tasks mt ON mt.id = page.id
         LEFT JOIN templates t ON mt.template_id = t.id
         LEFT JOIN mailing_lists ml ON mt.mail_list_id = ml.id
         CROSS JOIN LATERAL (SELECT count(*) FILTER (WHERE q.status = 'pending')    AS pending,
                                    count(*) FILTER (WHERE q.status = 'processing') AS processing,
                                    count(*) FILTER (WHERE q.status = 'sent')       AS sent,
                                    count(*) FILTER (WHERE q.status = 'failed')     AS failed
                             FROM mail_queue q
                             WHERE q.task_id = mt.id) rc
         LEFT JOIN mail_queue single
                   ON single.id = (SELECT q.id
                                   FROM mail_queue q
                                   WHERE mt.mail_list_id IS NULL
                                     AND q.task_id = mt.id
                                   ORDER BY q.created_at, q.id
                                   LIMIT 1)
ORDER BY mt.created_at DESC, mt.id DESC
`

type ListMailTaskSendsParams struct {
	Limit  int32      `json:"limit"`
	Offset int32      `json:"offset"`
	TaskID *uuid.UUID `json:"task_id"`
	Status *string    `json:"status"`
}

type ListMailTaskSendsRow struct {
	ID                      uuid.UUID  `json:"id"`
	SentBy                  string     `json:"sent_by"`
	TemplateID              *uuid.UUID `json:"template_id"`
	MailListID              *uuid.UUID `json:"mail_list_id"`
	BodyVariables           []byte     `json:"body_variables"`
	CreatedAt               time.Time  `json:"created_at"`
	TemplateName            *string    `json:"template_name"`
	TemplateKey             *string    `json:"template_key"`
	MailListName            *string    `json:"mail_list_name"`
	InternalMailList        bool       `json:"internal_mail_list"`
	Status                  string     `json:"status"`
	Pending                 int64      `json:"pending"`
	Processing              int64      `json:"processing"`
	Sent                    int64      `json:"sent"`
	Failed                  int64      `json:"failed"`
	SingleRecipientFullName *string    `json:"single_recipient_full_name"`
	SingleRecipientEmail    *string    `json:"single_recipient_email"`
}

// A send as every screen shows it — the home screen, the send list and a
// send's own page: the task, the template it used, who it went to, its status
// as mail_task_status derives it, and its recipients by status. A NULL task_id
// lists every send and a NULL status every status. The page is cut first so
// only its rows are counted.
func (q *Queries) ListMailTaskSends(ctx context.Context, arg ListMailTaskSendsParams) ([]ListMailTaskSendsRow, error) {
	rows, err := q.db.Query(ctx, listMailTaskSends,
		arg.Limit,
		arg.Offset,
		arg.TaskID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMailTaskSendsRow
	for rows.Next() {
		var i ListMailTaskSendsRow
		if err := rows.Scan(
			&i.ID,
			&i.SentBy,
			&i.TemplateID,
			&i.MailListID,
			&i.BodyVariables,
			&i.CreatedAt,
			&i.TemplateName,
			&i.TemplateKey,
			&i.MailListName,
			&i.InternalMailList,
			&i.Status,
			&i.Pending,
			&i.Processing,
			&i.Sent,
			&i.Failed,
			&i.SingleRecipientFullName,
			&i.SingleRecipientEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedMainModes = `-- name: ListPublishedMainModes :many
SELECT t.id AS template_id, v.main_mode
FROM templates t
         JOIN template_versions v ON v.id = t.published_version_id
WHERE t.id = ANY ($1::uuid[])
`

type ListPublishedMainModesRow struct {
	TemplateID uuid.UUID     `json:"template_id"`
	MainMode   AuthoringMode `json:"main_mode"`
}

// The Authoring mode of each template's Main source as it is sent: its
// published version's.
func (q *Queries) ListPublishedMainModes(ctx context.Context, templateIds []uuid.UUID) ([]ListPublishedMainModesRow, error) {
	rows, err := q.db.Query(ctx, listPublishedMainModes, templateIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedMainModesRow
	for rows.Next() {
		var i ListPublishedMainModesRow
		if err := rows.Scan(&i.TemplateID, &i.MainMode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateDrafts = `-- name: ListTemplateDrafts :many
SELECT id, template_id, seq, subject, requested_subject, main_mode, author_kind, author_sub, author_name, created_at, published_at, base_version_id, is_current, discarded_at
FROM template_version_summaries s
WHERE s.id IN (SELECT DISTINCT ON (v.template_id, v.author_sub) v.id
               FROM template_versions v
               WHERE v.template_id = ANY ($1::uuid[])
                 AND v.author_kind = 'operator'
               ORDER BY v.template_id, v.author_sub, v.seq DESC)
  AND s.published_at IS NULL
  AND s.discarded_at IS NULL
ORDER BY s.template_id, s.seq DESC
`

// Each operator's draft in progress on the given templates, newest first: the
// newest version an operator wrote of a template, when it is neither published
// nor discarded. An operator's later version supersedes their earlier drafts,
// so those are not listed, and discarding their newest leaves them none; a
// draft that someone else's publish made stale still is listed, until its
// author writes again or discards it.
func (q *Queries) ListTemplateDrafts(ctx context.Context, templateIds []uuid.UUID) ([]TemplateVersionSummary, error) {
	rows, err := q.db.Query(ctx, listTemplateDrafts, templateIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TemplateVersionSummary
	for rows.Next() {
		var i TemplateVersionSummary
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.Seq,
			&i.Subject,
			&i.RequestedSubject,
			&i.MainMode,
			&i.AuthorKind,
			&i.AuthorSub,
			&i.AuthorName,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.BaseVersionID,
			&i.IsCurrent,
			&i.DiscardedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateVersions = `-- name: ListTemplateVersions :many
SELECT id, template_id, seq, subject, requested_subject, main_mode, author_kind, author_sub, author_name, created_at, published_at, base_version_id, is_current, discarded_at
FROM template_version_summaries
WHERE template_id = $1
  AND ($4::boolean IS NULL OR (published_at IS NOT NULL) = $4::boolean)
ORDER BY seq DESC
LIMIT $2 OFFSET $3
`

type ListTemplateVersionsParams struct {
	TemplateID uuid.UUID `json:"template_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
	Published  *bool     `json:"published"`
}

// A template's Mail template versions, newest first, without their sources or
// render. A NULL published lists every version; true only published ones,
// false only drafts, discarded ones included.
func (q *Queries) ListTemplateVersions(ctx context.Context, arg ListTemplateVersionsParams) ([]TemplateVersionSummary, error) {
	rows, err := q.db.Query(ctx, listTemplateVersions,
		arg.TemplateID,
		arg.Limit,
		arg.Offset,
		arg.Published,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TemplateVersionSummary
	for rows.Next() {
		var i TemplateVersionSummary
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.Seq,
			&i.Subject,
			&i.RequestedSubject,
			&i.MainMode,
			&i.AuthorKind,
			&i.AuthorSub,
			&i.AuthorName,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.BaseVersionID,
			&i.IsCurrent,
			&i.DiscardedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTemplate = `-- name: LockTemplate :one
SELECT id, name, html_content, plain_text_content, react_email_content, created_at, updated_at, subject, archived_at, archived_by, key, system, published_version_id, contract_required_variables, operator_required_variables
FROM templates
WHERE id = $1
  AND archived_at IS NULL
    FOR UPDATE
`

// Takes a template row's lock for a write that does not change the row first —
// saving a draft, restoring a version, publishing, discarding. A version is
// numbered after the lock is taken, and the old panel's and the seed's writes
// take the same lock by updating the row, so every writer of one template
// numbers its version in turn. An archived template is not found here, as it
// is not for any other write.
func (q *Queries) LockTemplate(ctx context.Context, id uuid.UUID) (Template, error) {
	row := q.db.QueryRow(ctx, lockTemplate, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HtmlContent,
		&i.PlainTextContent,
		&i.ReactEmailContent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subject,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.Key,
		&i.System,
		&i.PublishedVersionID,
		&i.ContractRequiredVariables,
		&i.OperatorRequiredVariables,
	)
	return i, err
}

const processQueueItems = `-- name: ProcessQueueItems :many
UPDATE mail_queue
SET status = 'processing'
WHERE id IN (SELECT id
             FROM mail_queue
             WHERE status = 'pending'
               AND next_attempt_at <= NOW()
             ORDER BY next_attempt_at, created_at
             LIMIT 100 FOR UPDATE SKIP LOCKED)
RETURNING id, task_id, recipient_full_name, recipient_email, subject, body, body_html, status, error, created_at, attempts, next_attempt_at
`

func (q *Queries) ProcessQueueItems(ctx context.Context) ([]MailQueue, error) {
	rows, err := q.db.Query(ctx, processQueueItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MailQueue
	for rows.Next() {
		var i MailQueue
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.RecipientFullName,
			&i.RecipientEmail,
			&i.Subject,
			&i.Body,
			&i.BodyHtml,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.Attempts,
			&i.NextAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishTemplateDraft = `-- name: PublishTemplateDraft :one
WITH published AS (
    UPDATE template_versions v
        SET published_at = NOW()
        WHERE v.id = $1
            AND v.template_id = $2
            AND v.published_at IS NULL
            AND v.discarded_at IS NULL
        RETURNING v.id, v.template_id, v.subject, v.jsx_source, v.main_mode, v.html_content, v.plain_text_content)
UPDATE templates t
SET subject              = p.subject,
    html_content         = p.html_content,
    plain_text_content   = p.plain_text_content,
    react_email_content  = CASE WHEN p.main_mode = 'jsx' THEN p.jsx_source ELSE '' END,
    published_version_id = p.id,
    updated_at           = NOW()
FROM published p
WHERE t.id = p.template_id
RETURNING t.id, t.name, t.html_content, t.plain_text_content, t.react_email_content, t.created_at, t.updated_at, t.subject, t.archived_at, t.archived_by, t.key, t.system, t.published_version_id, t.contract_required_variables, t.operator_required_variables
`

type PublishTemplateDraftParams struct {
	VersionID  uuid.UUID `json:"version_id"`
	TemplateID uuid.UUID `json:"template_id"`
}

// Publishes a draft: marks it published and copies it onto the template row,
// which the send path reads — its subject and its render. react_email_content,
// the column the old panel edits, gets the JSX source only when JSX is the
// Main source, and an empty string otherwise. The old panel re-renders any JSX
// it finds there and saves that render as the body, and the expand step would
// then make JSX the Main source: a JSX source kept beside another Main source
// would reach live mail without anyone choosing it. With nothing there, the
// old panel refuses to save (it never saves an empty JSX source), so a
// template whose Main source is not JSX is edited in the editor only. The
// caller holds the row's lock and has checked that the version is a draft of
// this template.
func (q *Queries) PublishTemplateDraft(ctx context.Context, arg PublishTemplateDraftParams) (Template, error) {
	row := q.db.QueryRow(ctx, publishTemplateDraft, arg.VersionID, arg.TemplateID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HtmlContent,
		&i.PlainTextContent,
		&i.ReactEmailContent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subject,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.Key,
		&i.System,
		&i.PublishedVersionID,
		&i.ContractRequiredVariables,
		&i.OperatorRequiredVariables,
	)
	return i, err
}

const recordTemplateDraft = `-- name: RecordTemplateDraft :one
WITH repeated AS (SELECT v.id
                  FROM template_versions v
                  WHERE v.id = $1::uuid
                    AND (v.subject, v.jsx_source, v.visual_source, v.html_source, v.main_mode, v.html_content,
                         v.plain_text_content)
                      IS NOT DISTINCT FROM
                        ($2::text, $3::text, $4::jsonb,
                         $5::text, $6::authoring_mode, $7::text,
                         $8::text)),
     written AS (
         INSERT INTO template_versions (template_id, seq, subject, jsx_source, visual_source, html_source, main_mode,
                                        html_content, plain_text_content, author_kind, author_sub, author_name,
                                        base_version_id)
             SELECT $9::uuid,
                    COALESCE((SELECT max(v.seq) FROM template_versions v WHERE v.template_id = $9::uuid),
                             0) + 1,
                    $2::text,
                    $3::text,
                    $4::jsonb,
                    $5::text,
                    $6::authoring_mode,
                    $7::text,
                    $8::text,
                    'operator',
                    $10::text,
                    $11::text,
                    $12::uuid
             WHERE NOT EXISTS (SELECT 1 FROM repeated)
             RETURNING id)
SELECT id, true AS written
FROM written
UNION ALL
SELECT id, false AS written
FROM repeated
`

type RecordTemplateDraftParams struct {
	ContinuedID      *uuid.UUID    `json:"continued_id"`
	Subject          string        `json:"subject"`
	JsxSource        *string       `json:"jsx_source"`
	VisualSource     []byte        `json:"visual_source"`
	HtmlSource       *string       `json:"html_source"`
	MainMode         AuthoringMode `json:"main_mode"`
	HtmlContent      string        `json:"html_content"`
	PlainTextContent string        `json:"plain_text_content"`
	TemplateID       uuid.UUID     `json:"template_id"`
	AuthorSub        *string       `json:"author_sub"`
	AuthorName       *string       `json:"author_name"`
	BaseVersionID    *uuid.UUID    `json:"base_version_id"`
}

type RecordTemplateDraftRow struct {
	ID      uuid.UUID `json:"id"`
	Written bool      `json:"written"`
}

// Writes an operator's draft, numbered after the template's last version,
// unless the version it continues holds exactly this content already —
// subject, every source, Main source and render, a Visual document compared
// as JSON rather than as text. Returns the draft it wrote, or the version it
// would have repeated, and whether it wrote one. The caller holds the template
// row's lock (LockTemplate).
func (q *Queries) RecordTemplateDraft(ctx context.Context, arg RecordTemplateDraftParams) (RecordTemplateDraftRow, error) {
	row := q.db.QueryRow(ctx, recordTemplateDraft,
		arg.ContinuedID,
		arg.Subject,
		arg.JsxSource,
		arg.VisualSource,
		arg.HtmlSource,
		arg.MainMode,
		arg.HtmlContent,
		arg.PlainTextContent,
		arg.TemplateID,
		arg.AuthorSub,
		arg.AuthorName,
		arg.BaseVersionID,
	)
	var i RecordTemplateDraftRow
	err := row.Scan(&i.ID, &i.Written)
	return i, err
}

const recordTemplateRowAsVersion = `-- name: RecordTemplateRowAsVersion :execrows
WITH written AS (SELECT t.id,
                        t.subject,
                        t.html_content,
                        t.plain_text_content,
                        t.published_version_id,
                        template_jsx_source(t.react_email_content) AS jsx_source
                 FROM templates t
                 WHERE t.id = $1),
     candidate AS (SELECT w.id                                                        AS template_id,
                          w.subject,
                          COALESCE(w.jsx_source, p.jsx_source)                        AS jsx_source,
                          p.visual_source,
                          CASE
                              WHEN body.kept OR w.jsx_source IS NOT NULL THEN p.html_source
                              ELSE w.html_content
                              END                                                     AS html_source,
                          CASE
                              WHEN body.kept THEN p.main_mode
                              WHEN w.jsx_source IS NOT NULL THEN 'jsx'::authoring_mode
                              ELSE 'html'::authoring_mode
                              END                                                     AS main_mode,
                          w.html_content,
                          w.plain_text_content,
                          p.id                                                        AS published_id,
                          (p.subject, p.jsx_source, p.visual_source, p.html_source, p.main_mode,
                           p.html_content, p.plain_text_content)                      AS published_content
                   FROM written w
                            LEFT JOIN template_versions p ON p.id = w.published_version_id
                            CROSS JOIN LATERAL (SELECT p.id IS NOT NULL
                                                           AND w.html_content = p.html_content
                                                           AND w.plain_text_content = p.plain_text_content
                                                           AND w.jsx_source IS NOT DISTINCT FROM p.jsx_source AS kept) body),
     version AS (
         INSERT INTO template_versions (template_id, seq, subject, jsx_source, visual_source, html_source, main_mode,
                                        html_content, plain_text_content, author_kind, author_sub, author_name,
                                        requested_subject, published_at, base_version_id)
             SELECT c.template_id,
                    COALESCE((SELECT max(v.seq) FROM template_versions v WHERE v.template_id = c.template_id), 0) + 1,
                    c.subject,
                    c.jsx_source,
                    c.visual_source,
                    c.html_source,
                    c.main_mode,
                    c.html_content,
                    c.plain_text_content,
                    $2::template_author_kind,
                    $3::text,
                    $4::text,
                    $5::text,
                    NOW(),
                    c.published_id
             FROM candidate c
             WHERE c.published_id IS NULL
                OR (c.subject, c.jsx_source, c.visual_source, c.html_source, c.main_mode,
                    c.html_content, c.plain_text_content) IS DISTINCT FROM c.published_content
             RETURNING id, template_id)
UPDATE templates t
SET published_version_id = version.id
FROM version
WHERE t.id = version.template_id
`

type RecordTemplateRowAsVersionParams struct {
	TemplateID       uuid.UUID          `json:"template_id"`
	AuthorKind       TemplateAuthorKind `json:"author_kind"`
	AuthorSub        *string            `json:"author_sub"`
	AuthorName       *string            `json:"author_name"`
	RequestedSubject *string            `json:"requested_subject"`
}

// Records what a template row now holds as a new Mail template version,
// published at once, and makes the row a copy of it. This is the expand step
// for the writers that still write the row directly — the old panel's create
// and edit, and the Template seed's by-key upsert: each runs this after its
// row write, in the same transaction, so the version is what the row ended up
// with (a subject the upsert kept included), not what the request asked for.
//
// Those writers send a subject, a render and at most a JSX source, so the
// version starts from the published one and replaces only what they changed:
//   - The subject and the render are the row's.
//   - If the body — html_content, plain_text_content and the JSX source — is
//     the published version's, the Main source and every source stay as they
//     were: the old panel sends a stored body back untouched when only the
//     wording around it changed.
//   - Otherwise the body is new. react_email_content with a JSX source in it
//     (template_jsx_source decides) makes JSX the Main source with that text;
//     without one — the seed's pointer comment, or nothing — html_content is
//     the HTML source and the Main source.
//   - Sources in the other Authoring modes are carried over.
//
// A row with no published version yet — written before versions were kept,
// or by the old binary between the migration and this one — is taken as it
// now is. When the result is the published version over again, nothing is
// recorded: the write changed nothing a version holds (name is not one).
//
// The version is numbered after the template's last one; the row write before
// this holds the row's lock, so two writers cannot take the same number. Its
// base is the version the row was a copy of until now. A Template seed's
// version also keeps the subject the seed sent, requested_subject.
//
// Affects one row when a version was recorded and none when not.
func (q *Queries) RecordTemplateRowAsVersion(ctx context.Context, arg RecordTemplateRowAsVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordTemplateRowAsVersion,
		arg.TemplateID,
		arg.AuthorKind,
		arg.AuthorSub,
		arg.AuthorName,
		arg.RequestedSubject,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeOperatorRequiredVariable = `-- name: RemoveOperatorRequiredVariable :one
UPDATE templates
SET operator_required_variables = array_remove(operator_required_variables, $1::text)
WHERE id = $2
  AND archived_at IS NULL
RETURNING id, name, html_content, plain_text_content, react_email_content, created_at, updated_at, subject, archived_at, archived_by, key, system, published_version_id, contract_required_variables, operator_required_variables
`

type RemoveOperatorRequiredVariableParams struct {
	Name string    `json:"name"`
	ID   uuid.UUID `json:"id"`
}

// Releases a variable operators marked. It cannot release a contract one: the
// sets never share a name, so a contract name is simply not in the operators'
// set, and the caller sees it in the contract set it returns.
func (q *Queries) RemoveOperatorRequiredVariable(ctx context.Context, arg RemoveOperatorRequiredVariableParams) (Template, error) {
	row := q.db.QueryRow(ctx, removeOperatorRequiredVariable, arg.Name, arg.ID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HtmlContent,
		&i.PlainTextContent,
		&i.ReactEmailContent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subject,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.Key,
		&i.System,
		&i.PublishedVersionID,
		&i.ContractRequiredVariables,
		&i.OperatorRequiredVariables,
	)
	return i, err
}

const removeRecipientFromMailingListByID = `-- name: RemoveRecipientFromMailingListByID :exec
DELETE
FROM mailing_list_recipients
WHERE mail_list_id = $1
  AND recipient_id = $2
`

type RemoveRecipientFromMailingListByIDParams struct {
	MailListID  uuid.UUID `json:"mail_list_id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

func (q *Queries) RemoveRecipientFromMailingListByID(ctx context.Context, arg RemoveRecipientFromMailingListByIDParams) error {
	_, err := q.db.Exec(ctx, removeRecipientFromMailingListByID, arg.MailListID, arg.RecipientID)
	return err
}

const rescheduleMailQueueItem = `-- name: RescheduleMailQueueItem :one
UPDATE mail_queue
SET status          = 'pending',
    attempts        = attempts + 1,
    error           = $1::text,
    next_attempt_at = NOW() + ($2::int * INTERVAL '1 second')
WHERE id = $3
RETURNING attempts
`

type RescheduleMailQueueItemParams struct {
	Error        *string   `json:"error"`
	DelaySeconds int       `json:"delay_seconds"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) RescheduleMailQueueItem(ctx context.Context, arg RescheduleMailQueueItemParams) (int, error) {
	row := q.db.QueryRow(ctx, rescheduleMailQueueItem, arg.Error, arg.DelaySeconds, arg.ID)
	var attempts int
	err := row.Scan(&attempts)
	return attempts, err
}

const resetDeadJobs = `-- name: ResetDeadJobs :exec
UPDATE mail_queue
SET status = 'pending'
WHERE status = 'processing'
`

func (q *Queries) ResetDeadJobs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetDeadJobs)
	return err
}

const restoreMailingList = `-- name: RestoreMailingList :one
UPDATE mailing_lists
SET archived_at = NULL,
    archived_by = NULL,
    updated_at = CASE WHEN archived_at IS NULL THEN updated_at ELSE NOW() END
WHERE id = $1
RETURNING id, name, description, created_at, updated_at, archived_at, archived_by
`

func (q *Queries) RestoreMailingList(ctx context.Context, id uuid.UUID) (MailingList, error) {
	row := q.db.QueryRow(ctx, restoreMailingList, id)
	var i MailingList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.ArchivedBy,
	)
	return i, err
}

const restoreTemplate = `-- name: RestoreTemplate :one
UPDATE templates
SET archived_at = NULL,
    archived_by = NULL,
    updated_at = CASE WHEN archived_at IS NULL THEN updated_at ELSE NOW() END
WHERE id = $1
RETURNING id, name, html_content, plain_text_content, react_email_content, created_at, updated_at, subject, archived_at, archived_by, key, system, published_version_id, contract_required_variables, operator_required_variables
`

func (q *Queries) RestoreTemplate(ctx context.Context, id uuid.UUID) (Template, error) {
	row := q.db.QueryRow(ctx, restoreTemplate, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HtmlContent,
		&i.PlainTextContent,
		&i.ReactEmailContent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subject,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.Key,
		&i.System,
		&i.PublishedVersionID,
		&i.ContractRequiredVariables,
		&i.OperatorRequiredVariables,
	)
	return i, err
}

const setMailQueueItemFailed = `-- name: SetMailQueueItemFailed :exec
UPDATE mail_queue
SET status    = 'failed',
    attempts  = attempts + 1,
    error     = $2
WHERE id = $1
`

type SetMailQueueItemFailedParams struct {
	ID    uuid.UUID `json:"id"`
	Error *string   `json:"error"`
}

func (q *Queries) SetMailQueueItemFailed(ctx context.Context, arg SetMailQueueItemFailedParams) error {
	_, err := q.db.Exec(ctx, setMailQueueItemFailed, arg.ID, arg.Error)
	return err
}

const setMailQueueItemSent = `-- name: SetMailQueueItemSent :exec
UPDATE mail_queue
SET status    = 'sent',
    error     = NULL
WHERE id = $1
`

func (q *Queries) SetMailQueueItemSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setMailQueueItemSent, id)
	return err
}

const updateMailingList = `-- name: UpdateMailingList :one
UPDATE mailing_lists
SET name       = $2,
    updated_at = NOW()
WHERE id = $1
  AND archived_at IS NULL
RETURNING id, name, description, created_at, updated_at, archived_at, archived_by
`

type UpdateMailingListParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateMailingList(ctx context.Context, arg UpdateMailingListParams) (MailingList, error) {
	row := q.db.QueryRow(ctx, updateMailingList, arg.ID, arg.Name)
	var i MailingList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.ArchivedBy,
	)
	return i, err
}

const updateRecipient = `-- name: UpdateRecipient :one
UPDATE recipients
SET full_name  = $2,
    email      = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, full_name, email, created_at, updated_at
`

type UpdateRecipientParams struct {
	ID       uuid.UUID `json:"id"`
	FullName string    `json:"full_name"`
	Email    string    `json:"email"`
}

func (q *Queries) UpdateRecipient(ctx context.Context, arg UpdateRecipientParams) (Recipient, error) {
	row := q.db.QueryRow(ctx, updateRecipient, arg.ID, arg.FullName, arg.Email)
	var i Recipient
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates
SET name                = $2,
    subject             = $3,
    html_content        = $4,
    plain_text_content  = $5,
    react_email_content = $6,
    key                 = $7::text,
    updated_at          = NOW()
WHERE id = $1
  AND archived_at IS NULL
RETURNING id, name, html_content, plain_text_content, react_email_content, created_at, updated_at, subject, archived_at, archived_by, key, system, published_version_id, contract_required_variables, operator_required_variables
`

type UpdateTemplateParams struct {
	ID                uuid.UUID `json:"id"`
	Name              string    `json:"name"`
	Subject           string    `json:"subject"`
	HtmlContent       string    `json:"html_content"`
	PlainTextContent  string    `json:"plain_text_content"`
	ReactEmailContent string    `json:"react_email_content"`
	Key               *string   `json:"key"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, updateTemplate,
		arg.ID,
		arg.Name,
		arg.Subject,
		arg.HtmlContent,
		arg.PlainTextContent,
		arg.ReactEmailContent,
		arg.Key,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HtmlContent,
		&i.PlainTextContent,
		&i.ReactEmailContent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subject,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.Key,
		&i.System,
		&i.PublishedVersionID,
		&i.ContractRequiredVariables,
		&i.OperatorRequiredVariables,
	)
	return i, err
}

const upsertTemplateByKey = `-- name: UpsertTemplateByKey :one
INSERT INTO templates (key, name, subject, html_content, plain_text_content, react_email_content, system,
                       contract_required_variables)
VALUES ($1::text,
        $2::text,
        $3::text,
        $4::text,
        $5::text,
        $6::text,
        $7::boolean,
        COALESCE($8::jsonb, '[]'))
ON CONFLICT (key) DO UPDATE
    SET name                = EXCLUDED.name,
        html_content        = EXCLUDED.html_content,
        plain_text_content  = EXCLUDED.plain_text_content,
        react_email_content = EXCLUDED.react_email_content,
        system              = EXCLUDED.system,
        -- The contract set is the seed's, like the key: a seed that sends one
        -- replaces it (sorted, each name once, by the caller), a seed that
        -- sends none (NULL) leaves it. A name the contract now declares leaves
        -- the operators' set, so the two never share one and it shows as
        -- locked.
        contract_required_variables = COALESCE($8::jsonb,
                                               templates.contract_required_variables),
        operator_required_variables = ARRAY(SELECT name
                                            FROM unnest(templates.operator_required_variables) AS name
                                            WHERE name <> ALL (contract_variable_names(
                                                    COALESCE($8::jsonb,
                                                             templates.contract_required_variables)))
                                            ORDER BY name COLLATE "C"),
        archived_at         = NULL,
        archived_by         = NULL,
        updated_at          = NOW()
RETURNING id, name, html_content, plain_text_content, react_email_content, created_at, updated_at, subject, archived_at, archived_by, key, system, published_version_id, contract_required_variables, operator_required_variables
`

type UpsertTemplateByKeyParams struct {
	Key                       string `json:"key"`
	Name                      string `json:"name"`
	Subject                   string `json:"subject"`
	HtmlContent               string `json:"html_content"`
	PlainTextContent          string `json:"plain_text_content"`
	ReactEmailContent         string `json:"react_email_content"`
	System                    bool   `json:"system"`
	ContractRequiredVariables []byte `json:"contract_required_variables"`
}

// The seed owns a template's structure; an operator owns its subject. The repo
// seeds the subject once, on insert, and never writes over it again: ADR-0045
// moved Keycloak's system mail here so a wording change would stop costing a
// release, and re-seeding is frequent enough that overwriting the subject took
// that back silently. A subject fix made in the repo therefore does not reach a
// key that already exists; someone has to make it in SkyMail too.
func (q *Queries) UpsertTemplateByKey(ctx context.Context, arg UpsertTemplateByKeyParams) (Template, error) {
	row := q.db.QueryRow(ctx, upsertTemplateByKey,
		arg.Key,
		arg.Name,
		arg.Subject,
		arg.HtmlContent,
		arg.PlainTextContent,
		arg.ReactEmailContent,
		arg.System,
		arg.ContractRequiredVariables,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HtmlContent,
		&i.PlainTextContent,
		&i.ReactEmailContent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subject,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.Key,
		&i.System,
		&i.PublishedVersionID,
		&i.ContractRequiredVariables,
		&i.OperatorRequiredVariables,
	)
	return i, err
}
