// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addRecipientToMailingList = `-- name: AddRecipientToMailingList :one
WITH target_list AS (
    SELECT mailing_lists.id
    FROM mailing_lists
    WHERE mailing_lists.id = $1
      AND archived_at IS NULL
), recipient AS (
    INSERT INTO recipients (full_name, email)
        SELECT $2, $3 FROM target_list
        ON CONFLICT (email) DO UPDATE SET full_name = EXCLUDED.full_name
        RETURNING id, full_name, email, created_at, updated_at),
     association AS (
         INSERT INTO mailing_list_recipients (mail_list_id, recipient_id)
             SELECT $1, id FROM recipient
             ON CONFLICT DO NOTHING)
SELECT id, full_name, email, created_at, updated_at
FROM recipient
`

type AddRecipientToMailingListParams struct {
	MailListID uuid.UUID `json:"mail_list_id"`
	FullName   string    `json:"full_name"`
	Email      string    `json:"email"`
}

type AddRecipientToMailingListRow struct {
	ID        uuid.UUID `json:"id"`
	FullName  string    `json:"full_name"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) AddRecipientToMailingList(ctx context.Context, arg AddRecipientToMailingListParams) (AddRecipientToMailingListRow, error) {
	row := q.db.QueryRow(ctx, addRecipientToMailingList, arg.MailListID, arg.FullName, arg.Email)
	var i AddRecipientToMailingListRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const archiveMailingList = `-- name: ArchiveMailingList :one
UPDATE mailing_lists
SET archived_by = CASE
                      WHEN archived_at IS NULL THEN $1::text
                      ELSE archived_by
                  END,
    archived_at = COALESCE(archived_at, NOW()),
    updated_at = CASE WHEN archived_at IS NULL THEN NOW() ELSE updated_at END
WHERE id = $2
RETURNING id, name, description, created_at, updated_at, archived_at, archived_by
`

type ArchiveMailingListParams struct {
	ArchivedBy *string   `json:"archived_by"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) ArchiveMailingList(ctx context.Context, arg ArchiveMailingListParams) (MailingList, error) {
	row := q.db.QueryRow(ctx, archiveMailingList, arg.ArchivedBy, arg.ID)
	var i MailingList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.ArchivedBy,
	)
	return i, err
}

const archiveTemplate = `-- name: ArchiveTemplate :one
UPDATE templates
SET archived_by = CASE
                      WHEN archived_at IS NULL THEN $1::text
                      ELSE archived_by
                  END,
    archived_at = COALESCE(archived_at, NOW()),
    updated_at = CASE WHEN archived_at IS NULL THEN NOW() ELSE updated_at END
WHERE id = $2
  AND system = false
RETURNING id, name, html_content, plain_text_content, react_email_content, created_at, updated_at, subject, archived_at, archived_by, key, system
`

type ArchiveTemplateParams struct {
	ArchivedBy *string   `json:"archived_by"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) ArchiveTemplate(ctx context.Context, arg ArchiveTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, archiveTemplate, arg.ArchivedBy, arg.ID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HtmlContent,
		&i.PlainTextContent,
		&i.ReactEmailContent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subject,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.Key,
		&i.System,
	)
	return i, err
}

const countAllMailingListsIncludingArchived = `-- name: CountAllMailingListsIncludingArchived :one
SELECT count(*)
FROM mailing_lists
`

func (q *Queries) CountAllMailingListsIncludingArchived(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllMailingListsIncludingArchived)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllTemplatesIncludingArchived = `-- name: CountAllTemplatesIncludingArchived :one
SELECT count(*)
FROM templates
`

func (q *Queries) CountAllTemplatesIncludingArchived(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllTemplatesIncludingArchived)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countArchivedMailingLists = `-- name: CountArchivedMailingLists :one
SELECT count(*)
FROM mailing_lists
WHERE archived_at IS NOT NULL
`

func (q *Queries) CountArchivedMailingLists(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countArchivedMailingLists)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countArchivedTemplates = `-- name: CountArchivedTemplates :one
SELECT count(*)
FROM templates
WHERE archived_at IS NOT NULL
`

func (q *Queries) CountArchivedTemplates(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countArchivedTemplates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMailQueueItemsByTaskId = `-- name: CountMailQueueItemsByTaskId :one
SELECT count(*)
FROM mail_queue
WHERE task_id = $1
`

func (q *Queries) CountMailQueueItemsByTaskId(ctx context.Context, taskID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMailQueueItemsByTaskId, taskID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMailTasks = `-- name: CountMailTasks :one
SELECT count(*)
FROM mail_tasks
`

func (q *Queries) CountMailTasks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMailTasks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMailingLists = `-- name: CountMailingLists :one
SELECT count(*)
FROM mailing_lists
WHERE archived_at IS NULL
`

func (q *Queries) CountMailingLists(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMailingLists)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecipients = `-- name: CountRecipients :one
SELECT count(*)
FROM recipients
`

func (q *Queries) CountRecipients(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRecipients)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecipientsByMailingListId = `-- name: CountRecipientsByMailingListId :one
SELECT count(*)
FROM recipients r
         JOIN mailing_list_recipients mlr ON r.id = mlr.recipient_id
         JOIN mailing_lists ml ON ml.id = mlr.mail_list_id
WHERE mlr.mail_list_id = $1
  AND ml.archived_at IS NULL
`

func (q *Queries) CountRecipientsByMailingListId(ctx context.Context, mailListID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRecipientsByMailingListId, mailListID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTemplates = `-- name: CountTemplates :one
SELECT count(*)
FROM templates
WHERE archived_at IS NULL
`

func (q *Queries) CountTemplates(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTemplates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

type CreateMailQueueItemsParams struct {
	TaskID            uuid.UUID `json:"task_id"`
	RecipientFullName string    `json:"recipient_full_name"`
	RecipientEmail    string    `json:"recipient_email"`
	Subject           string    `json:"subject"`
	Body              string    `json:"body"`
	BodyHtml          *string   `json:"body_html"`
}

const createMailTask = `-- name: CreateMailTask :many
WITH active_source AS (
    SELECT t.id AS template_id, ml.id AS mail_list_id
    FROM templates t
             JOIN mailing_lists ml ON ml.id = $1::uuid
    WHERE t.id = $2::uuid
      AND t.archived_at IS NULL
      AND ml.archived_at IS NULL
), inserted_task AS (
    INSERT INTO mail_tasks (sent_by, template_id, mail_list_id, body_variables)
        SELECT $3, template_id, mail_list_id, $4 FROM active_source
        RETURNING id, sent_by, template_id, mail_list_id, body_variables, created_at
)
SELECT it.id               AS task_id,
       it.body_variables,
       t.name              AS template_name,
       t.subject           AS template_subject,
       t.html_content,
       t.plain_text_content,
       r.full_name         AS recipient_full_name,
       r.email             AS recipient_email
FROM inserted_task it
         JOIN templates t ON it.template_id = t.id
         JOIN mailing_list_recipients mlr ON it.mail_list_id = mlr.mail_list_id
         JOIN recipients r ON mlr.recipient_id = r.id
`

type CreateMailTaskParams struct {
	MailListID    *uuid.UUID `json:"mail_list_id"`
	TemplateID    *uuid.UUID `json:"template_id"`
	SentBy        string     `json:"sent_by"`
	BodyVariables []byte     `json:"body_variables"`
}

type CreateMailTaskRow struct {
	TaskID            uuid.UUID `json:"task_id"`
	BodyVariables     []byte    `json:"body_variables"`
	TemplateName      string    `json:"template_name"`
	TemplateSubject   string    `json:"template_subject"`
	HtmlContent       string    `json:"html_content"`
	PlainTextContent  string    `json:"plain_text_content"`
	RecipientFullName string    `json:"recipient_full_name"`
	RecipientEmail    string    `json:"recipient_email"`
}

func (q *Queries) CreateMailTask(ctx context.Context, arg CreateMailTaskParams) ([]CreateMailTaskRow, error) {
	rows, err := q.db.Query(ctx, createMailTask,
		arg.MailListID,
		arg.TemplateID,
		arg.SentBy,
		arg.BodyVariables,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreateMailTaskRow
	for rows.Next() {
		var i CreateMailTaskRow
		if err := rows.Scan(
			&i.TaskID,
			&i.BodyVariables,
			&i.TemplateName,
			&i.TemplateSubject,
			&i.HtmlContent,
			&i.PlainTextContent,
			&i.RecipientFullName,
			&i.RecipientEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createMailingList = `-- name: CreateMailingList :one
INSERT INTO mailing_lists (name)
VALUES ($1)
RETURNING id, name, description, created_at, updated_at, archived_at, archived_by
`

func (q *Queries) CreateMailingList(ctx context.Context, name string) (MailingList, error) {
	row := q.db.QueryRow(ctx, createMailingList, name)
	var i MailingList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.ArchivedBy,
	)
	return i, err
}

const createSingleMailTask = `-- name: CreateSingleMailTask :one
WITH active_template AS (
    SELECT templates.id
    FROM templates
    WHERE templates.id = $3::uuid
      AND archived_at IS NULL
), inserted_task AS (
    INSERT INTO mail_tasks (sent_by, template_id, body_variables)
        SELECT $4, id, $5 FROM active_template
        RETURNING id, sent_by, template_id, mail_list_id, body_variables, created_at
)
SELECT it.id               AS task_id,
       it.body_variables,
       t.name              AS template_name,
       t.subject           AS template_subject,
       t.html_content,
       t.plain_text_content,
       $1::text AS recipient_full_name,
       $2::text AS recipient_email
FROM inserted_task it
         JOIN templates t ON it.template_id = t.id
`

type CreateSingleMailTaskParams struct {
	RecipientFullName string     `json:"recipient_full_name"`
	RecipientEmail    string     `json:"recipient_email"`
	TemplateID        *uuid.UUID `json:"template_id"`
	SentBy            string     `json:"sent_by"`
	BodyVariables     []byte     `json:"body_variables"`
}

type CreateSingleMailTaskRow struct {
	TaskID            uuid.UUID `json:"task_id"`
	BodyVariables     []byte    `json:"body_variables"`
	TemplateName      string    `json:"template_name"`
	TemplateSubject   string    `json:"template_subject"`
	HtmlContent       string    `json:"html_content"`
	PlainTextContent  string    `json:"plain_text_content"`
	RecipientFullName string    `json:"recipient_full_name"`
	RecipientEmail    string    `json:"recipient_email"`
}

func (q *Queries) CreateSingleMailTask(ctx context.Context, arg CreateSingleMailTaskParams) (CreateSingleMailTaskRow, error) {
	row := q.db.QueryRow(ctx, createSingleMailTask,
		arg.RecipientFullName,
		arg.RecipientEmail,
		arg.TemplateID,
		arg.SentBy,
		arg.BodyVariables,
	)
	var i CreateSingleMailTaskRow
	err := row.Scan(
		&i.TaskID,
		&i.BodyVariables,
		&i.TemplateName,
		&i.TemplateSubject,
		&i.HtmlContent,
		&i.PlainTextContent,
		&i.RecipientFullName,
		&i.RecipientEmail,
	)
	return i, err
}

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (name, subject, html_content, plain_text_content, react_email_content, key)
VALUES ($1, $2, $3, $4, $5, $6::text)
RETURNING id, name, html_content, plain_text_content, react_email_content, created_at, updated_at, subject, archived_at, archived_by, key, system
`

type CreateTemplateParams struct {
	Name              string  `json:"name"`
	Subject           string  `json:"subject"`
	HtmlContent       string  `json:"html_content"`
	PlainTextContent  string  `json:"plain_text_content"`
	ReactEmailContent string  `json:"react_email_content"`
	Key               *string `json:"key"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.Name,
		arg.Subject,
		arg.HtmlContent,
		arg.PlainTextContent,
		arg.ReactEmailContent,
		arg.Key,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HtmlContent,
		&i.PlainTextContent,
		&i.ReactEmailContent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subject,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.Key,
		&i.System,
	)
	return i, err
}

const getAllMailTasks = `-- name: GetAllMailTasks :many
SELECT mt.id, mt.sent_by, mt.template_id, mt.mail_list_id, mt.body_variables, mt.created_at,
       t.name  AS template_name,
       ml.name AS mail_list_name
FROM mail_tasks mt
         LEFT JOIN templates t ON mt.template_id = t.id
         LEFT JOIN mailing_lists ml ON mt.mail_list_id = ml.id
ORDER BY mt.created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllMailTasksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetAllMailTasksRow struct {
	ID            uuid.UUID  `json:"id"`
	SentBy        string     `json:"sent_by"`
	TemplateID    *uuid.UUID `json:"template_id"`
	MailListID    *uuid.UUID `json:"mail_list_id"`
	BodyVariables []byte     `json:"body_variables"`
	CreatedAt     time.Time  `json:"created_at"`
	TemplateName  *string    `json:"template_name"`
	MailListName  *string    `json:"mail_list_name"`
}

func (q *Queries) GetAllMailTasks(ctx context.Context, arg GetAllMailTasksParams) ([]GetAllMailTasksRow, error) {
	rows, err := q.db.Query(ctx, getAllMailTasks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllMailTasksRow
	for rows.Next() {
		var i GetAllMailTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.SentBy,
			&i.TemplateID,
			&i.MailListID,
			&i.BodyVariables,
			&i.CreatedAt,
			&i.TemplateName,
			&i.MailListName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllMailingLists = `-- name: GetAllMailingLists :many
SELECT id, name, description, created_at, updated_at, archived_at, archived_by
FROM mailing_lists
WHERE archived_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllMailingListsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllMailingLists(ctx context.Context, arg GetAllMailingListsParams) ([]MailingList, error) {
	rows, err := q.db.Query(ctx, getAllMailingLists, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MailingList
	for rows.Next() {
		var i MailingList
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.ArchivedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllMailingListsIncludingArchived = `-- name: GetAllMailingListsIncludingArchived :many
SELECT id, name, description, created_at, updated_at, archived_at, archived_by
FROM mailing_lists
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllMailingListsIncludingArchivedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllMailingListsIncludingArchived(ctx context.Context, arg GetAllMailingListsIncludingArchivedParams) ([]MailingList, error) {
	rows, err := q.db.Query(ctx, getAllMailingListsIncludingArchived, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MailingList
	for rows.Next() {
		var i MailingList
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.ArchivedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTemplates = `-- name: GetAllTemplates :many
SELECT id, name, html_content, plain_text_content, react_email_content, created_at, updated_at, subject, archived_at, archived_by, key, system
FROM templates
WHERE archived_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllTemplatesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllTemplates(ctx context.Context, arg GetAllTemplatesParams) ([]Template, error) {
	rows, err := q.db.Query(ctx, getAllTemplates, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HtmlContent,
			&i.PlainTextContent,
			&i.ReactEmailContent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Subject,
			&i.ArchivedAt,
			&i.ArchivedBy,
			&i.Key,
			&i.System,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTemplatesIncludingArchived = `-- name: GetAllTemplatesIncludingArchived :many
SELECT id, name, html_content, plain_text_content, react_email_content, created_at, updated_at, subject, archived_at, archived_by, key, system
FROM templates
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllTemplatesIncludingArchivedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllTemplatesIncludingArchived(ctx context.Context, arg GetAllTemplatesIncludingArchivedParams) ([]Template, error) {
	rows, err := q.db.Query(ctx, getAllTemplatesIncludingArchived, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HtmlContent,
			&i.PlainTextContent,
			&i.ReactEmailContent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Subject,
			&i.ArchivedAt,
			&i.ArchivedBy,
			&i.Key,
			&i.System,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchivedMailingLists = `-- name: GetArchivedMailingLists :many
SELECT id, name, description, created_at, updated_at, archived_at, archived_by
FROM mailing_lists
WHERE archived_at IS NOT NULL
ORDER BY archived_at DESC
LIMIT $1 OFFSET $2
`

type GetArchivedMailingListsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetArchivedMailingLists(ctx context.Context, arg GetArchivedMailingListsParams) ([]MailingList, error) {
	rows, err := q.db.Query(ctx, getArchivedMailingLists, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MailingList
	for rows.Next() {
		var i MailingList
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.ArchivedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchivedTemplates = `-- name: GetArchivedTemplates :many
SELECT id, name, html_content, plain_text_content, react_email_content, created_at, updated_at, subject, archived_at, archived_by, key, system
FROM templates
WHERE archived_at IS NOT NULL
ORDER BY archived_at DESC
LIMIT $1 OFFSET $2
`

type GetArchivedTemplatesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetArchivedTemplates(ctx context.Context, arg GetArchivedTemplatesParams) ([]Template, error) {
	rows, err := q.db.Query(ctx, getArchivedTemplates, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HtmlContent,
			&i.PlainTextContent,
			&i.ReactEmailContent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Subject,
			&i.ArchivedAt,
			&i.ArchivedBy,
			&i.Key,
			&i.System,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMailQueueItemsByTaskId = `-- name: GetMailQueueItemsByTaskId :many
SELECT id, recipient_full_name, recipient_email, status, error, attempts, next_attempt_at, created_at
FROM mail_queue
WHERE task_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetMailQueueItemsByTaskIdParams struct {
	TaskID uuid.UUID `json:"task_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type GetMailQueueItemsByTaskIdRow struct {
	ID                uuid.UUID           `json:"id"`
	RecipientFullName string              `json:"recipient_full_name"`
	RecipientEmail    string              `json:"recipient_email"`
	Status            NullMailQueueStatus `json:"status"`
	Error             *string             `json:"error"`
	Attempts          int                 `json:"attempts"`
	NextAttemptAt     time.Time           `json:"next_attempt_at"`
	CreatedAt         *time.Time          `json:"created_at"`
}

func (q *Queries) GetMailQueueItemsByTaskId(ctx context.Context, arg GetMailQueueItemsByTaskIdParams) ([]GetMailQueueItemsByTaskIdRow, error) {
	rows, err := q.db.Query(ctx, getMailQueueItemsByTaskId, arg.TaskID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMailQueueItemsByTaskIdRow
	for rows.Next() {
		var i GetMailQueueItemsByTaskIdRow
		if err := rows.Scan(
			&i.ID,
			&i.RecipientFullName,
			&i.RecipientEmail,
			&i.Status,
			&i.Error,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMailTaskById = `-- name: GetMailTaskById :one
SELECT mt.id, mt.sent_by, mt.template_id, mt.mail_list_id, mt.body_variables, mt.created_at,
       t.name  AS template_name,
       ml.name AS mail_list_name
FROM mail_tasks mt
         LEFT JOIN templates t ON mt.template_id = t.id
         LEFT JOIN mailing_lists ml ON mt.mail_list_id = ml.id
WHERE mt.id = $1
`

type GetMailTaskByIdRow struct {
	ID            uuid.UUID  `json:"id"`
	SentBy        string     `json:"sent_by"`
	TemplateID    *uuid.UUID `json:"template_id"`
	MailListID    *uuid.UUID `json:"mail_list_id"`
	BodyVariables []byte     `json:"body_variables"`
	CreatedAt     time.Time  `json:"created_at"`
	TemplateName  *string    `json:"template_name"`
	MailListName  *string    `json:"mail_list_name"`
}

func (q *Queries) GetMailTaskById(ctx context.Context, id uuid.UUID) (GetMailTaskByIdRow, error) {
	row := q.db.QueryRow(ctx, getMailTaskById, id)
	var i GetMailTaskByIdRow
	err := row.Scan(
		&i.ID,
		&i.SentBy,
		&i.TemplateID,
		&i.MailListID,
		&i.BodyVariables,
		&i.CreatedAt,
		&i.TemplateName,
		&i.MailListName,
	)
	return i, err
}

const getMailingListById = `-- name: GetMailingListById :one
SELECT id, name, description, created_at, updated_at, archived_at, archived_by
FROM mailing_lists
WHERE id = $1
  AND archived_at IS NULL
`

func (q *Queries) GetMailingListById(ctx context.Context, id uuid.UUID) (MailingList, error) {
	row := q.db.QueryRow(ctx, getMailingListById, id)
	var i MailingList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.ArchivedBy,
	)
	return i, err
}

const getMailingListByIdIncludingArchived = `-- name: GetMailingListByIdIncludingArchived :one
SELECT id, name, description, created_at, updated_at, archived_at, archived_by
FROM mailing_lists
WHERE id = $1
`

func (q *Queries) GetMailingListByIdIncludingArchived(ctx context.Context, id uuid.UUID) (MailingList, error) {
	row := q.db.QueryRow(ctx, getMailingListByIdIncludingArchived, id)
	var i MailingList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.ArchivedBy,
	)
	return i, err
}

const getRecipientByEmail = `-- name: GetRecipientByEmail :one
SELECT id, full_name, email, created_at, updated_at
FROM recipients
WHERE email = $1
`

func (q *Queries) GetRecipientByEmail(ctx context.Context, email string) (Recipient, error) {
	row := q.db.QueryRow(ctx, getRecipientByEmail, email)
	var i Recipient
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecipients = `-- name: GetRecipients :many
SELECT id, full_name, email, created_at, updated_at
FROM recipients
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetRecipientsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetRecipients(ctx context.Context, arg GetRecipientsParams) ([]Recipient, error) {
	rows, err := q.db.Query(ctx, getRecipients, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipient
	for rows.Next() {
		var i Recipient
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecipientsByMailingListId = `-- name: GetRecipientsByMailingListId :many
SELECT r.id, r.full_name, r.email, r.created_at, r.updated_at
FROM recipients r
         JOIN mailing_list_recipients mlr ON r.id = mlr.recipient_id
         JOIN mailing_lists ml ON ml.id = mlr.mail_list_id
WHERE mlr.mail_list_id = $1
  AND ml.archived_at IS NULL
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type GetRecipientsByMailingListIdParams struct {
	MailListID uuid.UUID `json:"mail_list_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) GetRecipientsByMailingListId(ctx context.Context, arg GetRecipientsByMailingListIdParams) ([]Recipient, error) {
	rows, err := q.db.Query(ctx, getRecipientsByMailingListId, arg.MailListID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipient
	for rows.Next() {
		var i Recipient
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTemplateById = `-- name: GetTemplateById :one
SELECT id, name, html_content, plain_text_content, react_email_content, created_at, updated_at, subject, archived_at, archived_by, key, system
FROM templates
WHERE id = $1
  AND archived_at IS NULL
`

func (q *Queries) GetTemplateById(ctx context.Context, id uuid.UUID) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateById, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HtmlContent,
		&i.PlainTextContent,
		&i.ReactEmailContent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subject,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.Key,
		&i.System,
	)
	return i, err
}

const getTemplateByIdIncludingArchived = `-- name: GetTemplateByIdIncludingArchived :one
SELECT id, name, html_content, plain_text_content, react_email_content, created_at, updated_at, subject, archived_at, archived_by, key, system
FROM templates
WHERE id = $1
`

func (q *Queries) GetTemplateByIdIncludingArchived(ctx context.Context, id uuid.UUID) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByIdIncludingArchived, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HtmlContent,
		&i.PlainTextContent,
		&i.ReactEmailContent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subject,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.Key,
		&i.System,
	)
	return i, err
}

const getTemplateByKey = `-- name: GetTemplateByKey :one
SELECT id, name, html_content, plain_text_content, react_email_content, created_at, updated_at, subject, archived_at, archived_by, key, system
FROM templates
WHERE key = $1
  AND archived_at IS NULL
`

func (q *Queries) GetTemplateByKey(ctx context.Context, key *string) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByKey, key)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HtmlContent,
		&i.PlainTextContent,
		&i.ReactEmailContent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subject,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.Key,
		&i.System,
	)
	return i, err
}

const insertMailTask = `-- name: InsertMailTask :one
INSERT INTO mail_tasks (sent_by, template_id, mail_list_id, body_variables)
SELECT $1, $2, $3, $4
FROM templates
WHERE templates.id = $2
  AND archived_at IS NULL
RETURNING mail_tasks.id, sent_by, template_id, mail_list_id, body_variables, created_at
`

type InsertMailTaskParams struct {
	SentBy        string     `json:"sent_by"`
	TemplateID    *uuid.UUID `json:"template_id"`
	MailListID    *uuid.UUID `json:"mail_list_id"`
	BodyVariables []byte     `json:"body_variables"`
}

func (q *Queries) InsertMailTask(ctx context.Context, arg InsertMailTaskParams) (MailTask, error) {
	row := q.db.QueryRow(ctx, insertMailTask,
		arg.SentBy,
		arg.TemplateID,
		arg.MailListID,
		arg.BodyVariables,
	)
	var i MailTask
	err := row.Scan(
		&i.ID,
		&i.SentBy,
		&i.TemplateID,
		&i.MailListID,
		&i.BodyVariables,
		&i.CreatedAt,
	)
	return i, err
}

const processQueueItems = `-- name: ProcessQueueItems :many
UPDATE mail_queue
SET status = 'processing'
WHERE id IN (SELECT id
             FROM mail_queue
             WHERE status = 'pending'
               AND next_attempt_at <= NOW()
             ORDER BY next_attempt_at, created_at
             LIMIT 100 FOR UPDATE SKIP LOCKED)
RETURNING id, task_id, recipient_full_name, recipient_email, subject, body, body_html, status, error, created_at, attempts, next_attempt_at
`

func (q *Queries) ProcessQueueItems(ctx context.Context) ([]MailQueue, error) {
	rows, err := q.db.Query(ctx, processQueueItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MailQueue
	for rows.Next() {
		var i MailQueue
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.RecipientFullName,
			&i.RecipientEmail,
			&i.Subject,
			&i.Body,
			&i.BodyHtml,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.Attempts,
			&i.NextAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRecipientFromMailingListByID = `-- name: RemoveRecipientFromMailingListByID :exec
DELETE
FROM mailing_list_recipients
WHERE mail_list_id = $1
  AND recipient_id = $2
`

type RemoveRecipientFromMailingListByIDParams struct {
	MailListID  uuid.UUID `json:"mail_list_id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

func (q *Queries) RemoveRecipientFromMailingListByID(ctx context.Context, arg RemoveRecipientFromMailingListByIDParams) error {
	_, err := q.db.Exec(ctx, removeRecipientFromMailingListByID, arg.MailListID, arg.RecipientID)
	return err
}

const rescheduleMailQueueItem = `-- name: RescheduleMailQueueItem :one
UPDATE mail_queue
SET status          = 'pending',
    attempts        = attempts + 1,
    error           = $1::text,
    next_attempt_at = NOW() + ($2::int * INTERVAL '1 second')
WHERE id = $3
RETURNING attempts
`

type RescheduleMailQueueItemParams struct {
	Error        *string   `json:"error"`
	DelaySeconds int       `json:"delay_seconds"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) RescheduleMailQueueItem(ctx context.Context, arg RescheduleMailQueueItemParams) (int, error) {
	row := q.db.QueryRow(ctx, rescheduleMailQueueItem, arg.Error, arg.DelaySeconds, arg.ID)
	var attempts int
	err := row.Scan(&attempts)
	return attempts, err
}

const resetDeadJobs = `-- name: ResetDeadJobs :exec
UPDATE mail_queue
SET status = 'pending'
WHERE status = 'processing'
`

func (q *Queries) ResetDeadJobs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetDeadJobs)
	return err
}

const restoreMailingList = `-- name: RestoreMailingList :one
UPDATE mailing_lists
SET archived_at = NULL,
    archived_by = NULL,
    updated_at = CASE WHEN archived_at IS NULL THEN updated_at ELSE NOW() END
WHERE id = $1
RETURNING id, name, description, created_at, updated_at, archived_at, archived_by
`

func (q *Queries) RestoreMailingList(ctx context.Context, id uuid.UUID) (MailingList, error) {
	row := q.db.QueryRow(ctx, restoreMailingList, id)
	var i MailingList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.ArchivedBy,
	)
	return i, err
}

const restoreTemplate = `-- name: RestoreTemplate :one
UPDATE templates
SET archived_at = NULL,
    archived_by = NULL,
    updated_at = CASE WHEN archived_at IS NULL THEN updated_at ELSE NOW() END
WHERE id = $1
RETURNING id, name, html_content, plain_text_content, react_email_content, created_at, updated_at, subject, archived_at, archived_by, key, system
`

func (q *Queries) RestoreTemplate(ctx context.Context, id uuid.UUID) (Template, error) {
	row := q.db.QueryRow(ctx, restoreTemplate, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HtmlContent,
		&i.PlainTextContent,
		&i.ReactEmailContent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subject,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.Key,
		&i.System,
	)
	return i, err
}

const setMailQueueItemFailed = `-- name: SetMailQueueItemFailed :exec
UPDATE mail_queue
SET status    = 'failed',
    attempts  = attempts + 1,
    error     = $2
WHERE id = $1
`

type SetMailQueueItemFailedParams struct {
	ID    uuid.UUID `json:"id"`
	Error *string   `json:"error"`
}

func (q *Queries) SetMailQueueItemFailed(ctx context.Context, arg SetMailQueueItemFailedParams) error {
	_, err := q.db.Exec(ctx, setMailQueueItemFailed, arg.ID, arg.Error)
	return err
}

const setMailQueueItemSent = `-- name: SetMailQueueItemSent :exec
UPDATE mail_queue
SET status    = 'sent',
    error     = NULL
WHERE id = $1
`

func (q *Queries) SetMailQueueItemSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setMailQueueItemSent, id)
	return err
}

const updateMailingList = `-- name: UpdateMailingList :one
UPDATE mailing_lists
SET name       = $2,
    updated_at = NOW()
WHERE id = $1
  AND archived_at IS NULL
RETURNING id, name, description, created_at, updated_at, archived_at, archived_by
`

type UpdateMailingListParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateMailingList(ctx context.Context, arg UpdateMailingListParams) (MailingList, error) {
	row := q.db.QueryRow(ctx, updateMailingList, arg.ID, arg.Name)
	var i MailingList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.ArchivedBy,
	)
	return i, err
}

const updateRecipient = `-- name: UpdateRecipient :one
UPDATE recipients
SET full_name  = $2,
    email      = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, full_name, email, created_at, updated_at
`

type UpdateRecipientParams struct {
	ID       uuid.UUID `json:"id"`
	FullName string    `json:"full_name"`
	Email    string    `json:"email"`
}

func (q *Queries) UpdateRecipient(ctx context.Context, arg UpdateRecipientParams) (Recipient, error) {
	row := q.db.QueryRow(ctx, updateRecipient, arg.ID, arg.FullName, arg.Email)
	var i Recipient
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates
SET name                = $2,
    subject             = $3,
    html_content        = $4,
    plain_text_content  = $5,
    react_email_content = $6,
    key                 = $7::text,
    updated_at          = NOW()
WHERE id = $1
  AND archived_at IS NULL
RETURNING id, name, html_content, plain_text_content, react_email_content, created_at, updated_at, subject, archived_at, archived_by, key, system
`

type UpdateTemplateParams struct {
	ID                uuid.UUID `json:"id"`
	Name              string    `json:"name"`
	Subject           string    `json:"subject"`
	HtmlContent       string    `json:"html_content"`
	PlainTextContent  string    `json:"plain_text_content"`
	ReactEmailContent string    `json:"react_email_content"`
	Key               *string   `json:"key"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, updateTemplate,
		arg.ID,
		arg.Name,
		arg.Subject,
		arg.HtmlContent,
		arg.PlainTextContent,
		arg.ReactEmailContent,
		arg.Key,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HtmlContent,
		&i.PlainTextContent,
		&i.ReactEmailContent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subject,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.Key,
		&i.System,
	)
	return i, err
}

const upsertTemplateByKey = `-- name: UpsertTemplateByKey :one
INSERT INTO templates (key, name, subject, html_content, plain_text_content, react_email_content, system)
VALUES ($1::text,
        $2::text,
        $3::text,
        $4::text,
        $5::text,
        $6::text,
        $7::boolean)
ON CONFLICT (key) DO UPDATE
    SET name                = EXCLUDED.name,
        html_content        = EXCLUDED.html_content,
        plain_text_content  = EXCLUDED.plain_text_content,
        react_email_content = EXCLUDED.react_email_content,
        system              = EXCLUDED.system,
        archived_at         = NULL,
        archived_by         = NULL,
        updated_at          = NOW()
RETURNING id, name, html_content, plain_text_content, react_email_content, created_at, updated_at, subject, archived_at, archived_by, key, system
`

type UpsertTemplateByKeyParams struct {
	Key               string `json:"key"`
	Name              string `json:"name"`
	Subject           string `json:"subject"`
	HtmlContent       string `json:"html_content"`
	PlainTextContent  string `json:"plain_text_content"`
	ReactEmailContent string `json:"react_email_content"`
	System            bool   `json:"system"`
}

// The seed owns a template's structure; an operator owns its subject. The repo
// seeds the subject once, on insert, and never writes over it again: ADR-0045
// moved Keycloak's system mail here so a wording change would stop costing a
// release, and re-seeding is frequent enough that overwriting the subject took
// that back silently. A subject fix made in the repo therefore does not reach a
// key that already exists; someone has to make it in SkyMail too.
func (q *Queries) UpsertTemplateByKey(ctx context.Context, arg UpsertTemplateByKeyParams) (Template, error) {
	row := q.db.QueryRow(ctx, upsertTemplateByKey,
		arg.Key,
		arg.Name,
		arg.Subject,
		arg.HtmlContent,
		arg.PlainTextContent,
		arg.ReactEmailContent,
		arg.System,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HtmlContent,
		&i.PlainTextContent,
		&i.ReactEmailContent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subject,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.Key,
		&i.System,
	)
	return i, err
}
