// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Required variable sets are sorted byte by byte (COLLATE "C"), the order the
	// handler sorts a contract set in and a missing list comes in, whatever the
	// database's collation.
	//
	// Marks a variable of a template in use as required by operators. A name
	// already in either set changes nothing: one the contract declares is required
	// already, and stays the contract's. Takes the row's lock, so the caller can
	// check the body against the sets it returns before committing.
	AddOperatorRequiredVariable(ctx context.Context, arg AddOperatorRequiredVariableParams) (Template, error)
	AddRecipientToMailingList(ctx context.Context, arg AddRecipientToMailingListParams) (AddRecipientToMailingListRow, error)
	ArchiveMailingList(ctx context.Context, arg ArchiveMailingListParams) (MailingList, error)
	ArchiveTemplate(ctx context.Context, arg ArchiveTemplateParams) (Template, error)
	CountAllMailingListsIncludingArchived(ctx context.Context) (int64, error)
	CountAllTemplatesIncludingArchived(ctx context.Context) (int64, error)
	CountArchivedMailingLists(ctx context.Context) (int64, error)
	CountArchivedTemplates(ctx context.Context) (int64, error)
	CountMailQueueByStatus(ctx context.Context) (CountMailQueueByStatusRow, error)
	CountMailQueueItemsByTaskId(ctx context.Context, arg CountMailQueueItemsByTaskIdParams) (int64, error)
	CountMailTaskSends(ctx context.Context, status *string) (int64, error)
	CountMailTasks(ctx context.Context) (int64, error)
	// Sends by the status mail_task_status derives, over every send: the same
	// numbers CountMailTaskSends gives for each status filter.
	CountMailTasksByStatus(ctx context.Context) (CountMailTasksByStatusRow, error)
	CountMailingLists(ctx context.Context) (int64, error)
	CountRecipients(ctx context.Context) (int64, error)
	CountRecipientsByMailingListId(ctx context.Context, mailListID uuid.UUID) (int64, error)
	CountTemplateVersions(ctx context.Context, templateID uuid.UUID) (int64, error)
	CountTemplates(ctx context.Context) (int64, error)
	CreateMailQueueItems(ctx context.Context, arg []CreateMailQueueItemsParams) (int64, error)
	CreateMailTask(ctx context.Context, arg CreateMailTaskParams) ([]CreateMailTaskRow, error)
	CreateMailingList(ctx context.Context, name string) (MailingList, error)
	CreateSingleMailTask(ctx context.Context, arg CreateSingleMailTaskParams) (CreateSingleMailTaskRow, error)
	CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error)
	GetAllMailingLists(ctx context.Context, arg GetAllMailingListsParams) ([]MailingList, error)
	GetAllMailingListsIncludingArchived(ctx context.Context, arg GetAllMailingListsIncludingArchivedParams) ([]MailingList, error)
	GetAllTemplates(ctx context.Context, arg GetAllTemplatesParams) ([]Template, error)
	GetAllTemplatesIncludingArchived(ctx context.Context, arg GetAllTemplatesIncludingArchivedParams) ([]Template, error)
	GetArchivedMailingLists(ctx context.Context, arg GetArchivedMailingListsParams) ([]MailingList, error)
	GetArchivedTemplates(ctx context.Context, arg GetArchivedTemplatesParams) ([]Template, error)
	// A queue row has no sent time of its own. created_at — when that recipient's
	// mail was queued — stands in for it: the dispatcher is woken on enqueue, so a
	// mail that goes through on its first attempt leaves within seconds, and only a
	// retried one (the ladder tops out under eight minutes) can land later.
	// next_attempt_at is not used: every row older than the retry migration holds
	// that migration's timestamp in it.
	// Days are calendar days in time_zone; the series ends on as_of's day and has
	// one row per day, zero-filled.
	GetDailySentCounts(ctx context.Context, arg GetDailySentCountsParams) ([]GetDailySentCountsRow, error)
	// A send's recipients, newest first. A list send's rows come from one insert
	// and share a created_at, so the id breaks the tie: pages neither repeat nor
	// skip a recipient. A NULL status lists every recipient.
	GetMailQueueItemsByTaskId(ctx context.Context, arg GetMailQueueItemsByTaskIdParams) ([]GetMailQueueItemsByTaskIdRow, error)
	GetMailTaskById(ctx context.Context, id uuid.UUID) (GetMailTaskByIdRow, error)
	GetMailingListById(ctx context.Context, id uuid.UUID) (MailingList, error)
	GetMailingListByIdIncludingArchived(ctx context.Context, id uuid.UUID) (MailingList, error)
	GetRecipientByEmail(ctx context.Context, email string) (Recipient, error)
	GetRecipients(ctx context.Context, arg GetRecipientsParams) ([]Recipient, error)
	GetRecipientsByMailingListId(ctx context.Context, arg GetRecipientsByMailingListIdParams) ([]Recipient, error)
	GetTemplateById(ctx context.Context, id uuid.UUID) (Template, error)
	GetTemplateByIdIncludingArchived(ctx context.Context, id uuid.UUID) (Template, error)
	GetTemplateByKey(ctx context.Context, key *string) (Template, error)
	// One version of one template, whole. A version of another template is not
	// found here.
	GetTemplateVersion(ctx context.Context, arg GetTemplateVersionParams) (GetTemplateVersionRow, error)
	InsertMailTask(ctx context.Context, arg InsertMailTaskParams) (MailTask, error)
	// A send as every screen shows it — the home screen, the send list and a
	// send's own page: the task, the template it used, who it went to, its status
	// as mail_task_status derives it, and its recipients by status. A NULL task_id
	// lists every send and a NULL status every status. The page is cut first so
	// only its rows are counted.
	ListMailTaskSends(ctx context.Context, arg ListMailTaskSendsParams) ([]ListMailTaskSendsRow, error)
	// A template's Mail template versions, newest first, without their sources or
	// render.
	ListTemplateVersions(ctx context.Context, arg ListTemplateVersionsParams) ([]TemplateVersionSummary, error)
	ProcessQueueItems(ctx context.Context) ([]MailQueue, error)
	// Records what a template row now holds as a new Mail template version,
	// published at once, and makes the row a copy of it. This is the expand step
	// for the writers that still write the row directly — the old panel's create
	// and edit, and the Template seed's by-key upsert: each runs this after its
	// row write, in the same transaction, so the version is what the row ended up
	// with (a subject the upsert kept included), not what the request asked for.
	//
	// Those writers send a subject, a render and at most a JSX source, so the
	// version starts from the published one and replaces only what they changed:
	//   * The subject and the render are the row's.
	//   * If the body — html_content, plain_text_content and the JSX source — is
	//     the published version's, the Main source and every source stay as they
	//     were: the old panel sends a stored body back untouched when only the
	//     wording around it changed.
	//   * Otherwise the body is new. react_email_content with a JSX source in it
	//     (template_jsx_source decides) makes JSX the Main source with that text;
	//     without one — the seed's pointer comment, or nothing — html_content is
	//     the HTML source and the Main source.
	//   * Sources in the other Authoring modes are carried over.
	// A row with no published version yet — written before versions were kept,
	// or by the old binary between the migration and this one — is taken as it
	// now is. When the result is the published version over again, nothing is
	// recorded: the write changed nothing a version holds (name is not one).
	//
	// The version is numbered after the template's last one; the row write before
	// this holds the row's lock, so two writers cannot take the same number. Its
	// base is the version the row was a copy of until now. A Template seed's
	// version also keeps the subject the seed sent, requested_subject.
	//
	// Affects one row when a version was recorded and none when not.
	RecordTemplateRowAsVersion(ctx context.Context, arg RecordTemplateRowAsVersionParams) (int64, error)
	// Releases a variable operators marked. It cannot release a contract one: the
	// sets never share a name, so a contract name is simply not in the operators'
	// set, and the caller sees it in the contract set it returns.
	RemoveOperatorRequiredVariable(ctx context.Context, arg RemoveOperatorRequiredVariableParams) (Template, error)
	RemoveRecipientFromMailingListByID(ctx context.Context, arg RemoveRecipientFromMailingListByIDParams) error
	RescheduleMailQueueItem(ctx context.Context, arg RescheduleMailQueueItemParams) (int, error)
	ResetDeadJobs(ctx context.Context) error
	RestoreMailingList(ctx context.Context, id uuid.UUID) (MailingList, error)
	RestoreTemplate(ctx context.Context, id uuid.UUID) (Template, error)
	SetMailQueueItemFailed(ctx context.Context, arg SetMailQueueItemFailedParams) error
	SetMailQueueItemSent(ctx context.Context, id uuid.UUID) error
	UpdateMailingList(ctx context.Context, arg UpdateMailingListParams) (MailingList, error)
	UpdateRecipient(ctx context.Context, arg UpdateRecipientParams) (Recipient, error)
	UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error)
	// The seed owns a template's structure; an operator owns its subject. The repo
	// seeds the subject once, on insert, and never writes over it again: ADR-0045
	// moved Keycloak's system mail here so a wording change would stop costing a
	// release, and re-seeding is frequent enough that overwriting the subject took
	// that back silently. A subject fix made in the repo therefore does not reach a
	// key that already exists; someone has to make it in SkyMail too.
	UpsertTemplateByKey(ctx context.Context, arg UpsertTemplateByKeyParams) (Template, error)
}

var _ Querier = (*Queries)(nil)
