// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addRecipientToMailingList = `-- name: AddRecipientToMailingList :exec
WITH recipient AS (
    INSERT INTO recipients (full_name, email)
    VALUES ($2, $3)
    ON CONFLICT (email) DO UPDATE SET full_name = EXCLUDED.full_name
    RETURNING id
)
INSERT INTO mailing_list_recipients (mail_list_id, recipient_id)
VALUES ($1, recipient.id)
ON CONFLICT DO NOTHING
`

type AddRecipientToMailingListParams struct {
	MailListID uuid.UUID `json:"mail_list_id"`
	FullName   string    `json:"full_name"`
	Email      string    `json:"email"`
}

func (q *Queries) AddRecipientToMailingList(ctx context.Context, arg AddRecipientToMailingListParams) error {
	_, err := q.db.Exec(ctx, addRecipientToMailingList, arg.MailListID, arg.FullName, arg.Email)
	return err
}

const createMailingList = `-- name: CreateMailingList :one
INSERT INTO mailing_lists (name)
VALUES ($1)
RETURNING id, name, description, created_at, updated_at
`

func (q *Queries) CreateMailingList(ctx context.Context, name string) (MailingList, error) {
	row := q.db.QueryRow(ctx, createMailingList, name)
	var i MailingList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (name, html_content, plain_text_content)
VALUES ($1, $2, $3)
RETURNING id, name, html_content, plain_text_content, created_at, updated_at
`

type CreateTemplateParams struct {
	Name             string `json:"name"`
	HtmlContent      string `json:"html_content"`
	PlainTextContent string `json:"plain_text_content"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate, arg.Name, arg.HtmlContent, arg.PlainTextContent)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HtmlContent,
		&i.PlainTextContent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMailingList = `-- name: DeleteMailingList :exec
DELETE FROM mailing_lists WHERE id = $1
`

func (q *Queries) DeleteMailingList(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMailingList, id)
	return err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM templates WHERE id = $1
`

func (q *Queries) DeleteTemplate(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTemplate, id)
	return err
}

const getAllMailingLists = `-- name: GetAllMailingLists :many
SELECT id, name, description, created_at, updated_at FROM mailing_lists
`

func (q *Queries) GetAllMailingLists(ctx context.Context) ([]MailingList, error) {
	rows, err := q.db.Query(ctx, getAllMailingLists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MailingList
	for rows.Next() {
		var i MailingList
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTemplates = `-- name: GetAllTemplates :many
SELECT id, name, html_content, plain_text_content, created_at, updated_at FROM templates
`

func (q *Queries) GetAllTemplates(ctx context.Context) ([]Template, error) {
	rows, err := q.db.Query(ctx, getAllTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HtmlContent,
			&i.PlainTextContent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMailingListById = `-- name: GetMailingListById :one
SELECT id, name, description, created_at, updated_at FROM mailing_lists WHERE id = $1
`

func (q *Queries) GetMailingListById(ctx context.Context, id uuid.UUID) (MailingList, error) {
	row := q.db.QueryRow(ctx, getMailingListById, id)
	var i MailingList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecipientByEmail = `-- name: GetRecipientByEmail :one
SELECT id, full_name, email, created_at, updated_at FROM recipients WHERE email = $1
`

func (q *Queries) GetRecipientByEmail(ctx context.Context, email string) (Recipient, error) {
	row := q.db.QueryRow(ctx, getRecipientByEmail, email)
	var i Recipient
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecipients = `-- name: GetRecipients :many
SELECT id, full_name, email, created_at, updated_at FROM recipients
`

func (q *Queries) GetRecipients(ctx context.Context) ([]Recipient, error) {
	rows, err := q.db.Query(ctx, getRecipients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipient
	for rows.Next() {
		var i Recipient
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecipientsByMailingListId = `-- name: GetRecipientsByMailingListId :many
SELECT r.id, r.full_name, r.email, r.created_at, r.updated_at
FROM recipients r
JOIN mailing_list_recipients mlr ON r.id = mlr.recipient_id
WHERE mlr.mail_list_id = $1
`

func (q *Queries) GetRecipientsByMailingListId(ctx context.Context, mailListID uuid.UUID) ([]Recipient, error) {
	rows, err := q.db.Query(ctx, getRecipientsByMailingListId, mailListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipient
	for rows.Next() {
		var i Recipient
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTemplateById = `-- name: GetTemplateById :one
SELECT id, name, html_content, plain_text_content, created_at, updated_at FROM templates WHERE id = $1
`

func (q *Queries) GetTemplateById(ctx context.Context, id uuid.UUID) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateById, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HtmlContent,
		&i.PlainTextContent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeRecipientFromMailingListByID = `-- name: RemoveRecipientFromMailingListByID :exec
DELETE FROM mailing_list_recipients
WHERE mail_list_id = $1 AND recipient_id = $2
`

type RemoveRecipientFromMailingListByIDParams struct {
	MailListID  uuid.UUID `json:"mail_list_id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

func (q *Queries) RemoveRecipientFromMailingListByID(ctx context.Context, arg RemoveRecipientFromMailingListByIDParams) error {
	_, err := q.db.Exec(ctx, removeRecipientFromMailingListByID, arg.MailListID, arg.RecipientID)
	return err
}

const updateMailingList = `-- name: UpdateMailingList :one
UPDATE mailing_lists
SET name = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, created_at, updated_at
`

type UpdateMailingListParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateMailingList(ctx context.Context, arg UpdateMailingListParams) (MailingList, error) {
	row := q.db.QueryRow(ctx, updateMailingList, arg.ID, arg.Name)
	var i MailingList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRecipient = `-- name: UpdateRecipient :one
UPDATE recipients
SET full_name = $2, email = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, full_name, email, created_at, updated_at
`

type UpdateRecipientParams struct {
	ID       uuid.UUID `json:"id"`
	FullName string    `json:"full_name"`
	Email    string    `json:"email"`
}

func (q *Queries) UpdateRecipient(ctx context.Context, arg UpdateRecipientParams) (Recipient, error) {
	row := q.db.QueryRow(ctx, updateRecipient, arg.ID, arg.FullName, arg.Email)
	var i Recipient
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates
SET name = $2, html_content = $3, plain_text_content = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, html_content, plain_text_content, created_at, updated_at
`

type UpdateTemplateParams struct {
	ID               uuid.UUID `json:"id"`
	Name             string    `json:"name"`
	HtmlContent      string    `json:"html_content"`
	PlainTextContent string    `json:"plain_text_content"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, updateTemplate,
		arg.ID,
		arg.Name,
		arg.HtmlContent,
		arg.PlainTextContent,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HtmlContent,
		&i.PlainTextContent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
