services:
  skymail:
    container_name: skymail
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://skymail:${SKYMAIL_DB_PASSWORD:-postgres}@postgres:5432/skymail?sslmode=disable
      APP_PORT: "3000"
    env_file:
      - path: .env
        required: false
    restart: unless-stopped
    networks:
      - skylab

networks:
  skylab:
    external: true
