// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "components": {
        "schemas": {
            "apperrors.AppError": {
                "properties": {
                    "code": {
                        "type": "string"
                    },
                    "message": {
                        "type": "string"
                    },
                    "params": {
                        "additionalProperties": {},
                        "type": "object"
                    }
                },
                "type": "object"
            },
            "database.GetAllMailTasksRow": {
                "properties": {
                    "body_variables": {
                        "items": {
                            "type": "integer"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "created_at": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "mail_list_id": {
                        "type": "string"
                    },
                    "mail_list_name": {
                        "type": "string"
                    },
                    "sent_by": {
                        "type": "string"
                    },
                    "template_id": {
                        "type": "string"
                    },
                    "template_name": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "database.GetMailTaskByIdRow": {
                "properties": {
                    "body_variables": {
                        "items": {
                            "type": "integer"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "created_at": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "mail_list_id": {
                        "type": "string"
                    },
                    "mail_list_name": {
                        "type": "string"
                    },
                    "sent_by": {
                        "type": "string"
                    },
                    "template_id": {
                        "type": "string"
                    },
                    "template_name": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "database.MailQueue": {
                "properties": {
                    "body": {
                        "type": "string"
                    },
                    "body_html": {
                        "type": "string"
                    },
                    "created_at": {
                        "type": "string"
                    },
                    "error": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "recipient_email": {
                        "type": "string"
                    },
                    "recipient_full_name": {
                        "type": "string"
                    },
                    "status": {
                        "$ref": "#/components/schemas/database.NullMailQueueStatus"
                    },
                    "subject": {
                        "type": "string"
                    },
                    "task_id": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "database.MailQueueStatus": {
                "enum": [
                    "pending",
                    "processing",
                    "sent",
                    "failed"
                ],
                "type": "string",
                "x-enum-varnames": [
                    "MailQueueStatusPending",
                    "MailQueueStatusProcessing",
                    "MailQueueStatusSent",
                    "MailQueueStatusFailed"
                ]
            },
            "database.MailingList": {
                "properties": {
                    "created_at": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "updated_at": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "database.NullMailQueueStatus": {
                "properties": {
                    "mail_queue_status": {
                        "$ref": "#/components/schemas/database.MailQueueStatus"
                    },
                    "valid": {
                        "description": "Valid is true if MailQueueStatus is not NULL",
                        "type": "boolean"
                    }
                },
                "type": "object"
            },
            "database.Recipient": {
                "properties": {
                    "created_at": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "full_name": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "updated_at": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "database.Template": {
                "properties": {
                    "created_at": {
                        "type": "string"
                    },
                    "html_content": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "plain_text_content": {
                        "type": "string"
                    },
                    "react_email_content": {
                        "type": "string"
                    },
                    "subject": {
                        "type": "string"
                    },
                    "updated_at": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "requests.AddRecipient": {
                "properties": {
                    "email": {
                        "type": "string"
                    },
                    "full_name": {
                        "type": "string"
                    }
                },
                "required": [
                    "email",
                    "full_name"
                ],
                "type": "object"
            },
            "requests.CreateMailTask": {
                "properties": {
                    "body_variables": {
                        "additionalProperties": {},
                        "type": "object"
                    },
                    "mail_list_id": {
                        "type": "string"
                    },
                    "template_id": {
                        "type": "string"
                    }
                },
                "required": [
                    "mail_list_id",
                    "template_id"
                ],
                "type": "object"
            },
            "requests.CreateMailingList": {
                "properties": {
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "name"
                ],
                "type": "object"
            },
            "requests.CreateTemplate": {
                "properties": {
                    "html_content": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "plain_text_content": {
                        "type": "string"
                    },
                    "react_email_content": {
                        "type": "string"
                    },
                    "subject": {
                        "type": "string"
                    }
                },
                "required": [
                    "html_content",
                    "name",
                    "plain_text_content",
                    "react_email_content",
                    "subject"
                ],
                "type": "object"
            },
            "requests.UpdateMailingList": {
                "properties": {
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "name"
                ],
                "type": "object"
            },
            "requests.UpdateTemplate": {
                "properties": {
                    "html_content": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "plain_text_content": {
                        "type": "string"
                    },
                    "react_email_content": {
                        "type": "string"
                    },
                    "subject": {
                        "type": "string"
                    }
                },
                "required": [
                    "html_content",
                    "name",
                    "plain_text_content",
                    "react_email_content",
                    "subject"
                ],
                "type": "object"
            }
        }
    },
    "info": {
        "contact": {
            "email": "hello@enesgenc.dev",
            "name": "Enes Genç",
            "url": "https://enesgenc.dev"
        },
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "externalDocs": {
        "description": "",
        "url": ""
    },
    "paths": {
        "/mail_tasks": {
            "get": {
                "description": "Get a list of all mail tasks with pagination.",
                "parameters": [
                    {
                        "description": "Start index",
                        "in": "query",
                        "name": "_start",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "End index",
                        "in": "query",
                        "name": "_end",
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/database.GetAllMailTasksRow"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "List all mail tasks",
                "tags": [
                    "Mail"
                ]
            },
            "post": {
                "description": "Create a new mail task, process template variables, and queue emails for all recipients in the mailing list.",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "object"
                                    },
                                    {
                                        "$ref": "#/components/schemas/requests.CreateMailTask",
                                        "summary": "task",
                                        "description": "Mail task details"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "Mail task details",
                    "required": true
                },
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        },
                        "description": "Created"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Create a new mail task",
                "tags": [
                    "Mail"
                ]
            }
        },
        "/mail_tasks/{id}": {
            "get": {
                "description": "Get details of a specific mail task by its ID.",
                "parameters": [
                    {
                        "description": "Task ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/database.GetMailTaskByIdRow"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Not Found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Get a mail task by ID",
                "tags": [
                    "Mail"
                ]
            }
        },
        "/mail_tasks/{id}/queue": {
            "get": {
                "description": "Get a list of mail queue items associated with a specific task ID, with pagination.",
                "parameters": [
                    {
                        "description": "Task ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Start index",
                        "in": "query",
                        "name": "_start",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "End index",
                        "in": "query",
                        "name": "_end",
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/database.MailQueue"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Get mail queue items for a task",
                "tags": [
                    "Mail"
                ]
            }
        },
        "/mailing_lists": {
            "get": {
                "description": "Get a list of all mailing lists with pagination.",
                "parameters": [
                    {
                        "description": "Start index",
                        "in": "query",
                        "name": "_start",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "End index",
                        "in": "query",
                        "name": "_end",
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/database.MailingList"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "List all mailing lists",
                "tags": [
                    "Lists"
                ]
            },
            "post": {
                "description": "Create a new mailing list with the provided name.",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "object"
                                    },
                                    {
                                        "$ref": "#/components/schemas/requests.CreateMailingList",
                                        "summary": "list",
                                        "description": "List details"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "List details",
                    "required": true
                },
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/database.MailingList"
                                }
                            }
                        },
                        "description": "Created"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Create a new mailing list",
                "tags": [
                    "Lists"
                ]
            }
        },
        "/mailing_lists/{id}": {
            "delete": {
                "description": "Delete an existing mailing list by its ID.",
                "parameters": [
                    {
                        "description": "List ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Not Found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Delete a mailing list",
                "tags": [
                    "Lists"
                ]
            },
            "get": {
                "description": "Get details of a specific mailing list by its ID.",
                "parameters": [
                    {
                        "description": "List ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/database.MailingList"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Not Found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Get a mailing list by ID",
                "tags": [
                    "Lists"
                ]
            },
            "patch": {
                "description": "Update an existing mailing list with the provided ID and details.",
                "parameters": [
                    {
                        "description": "List ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "object"
                                    },
                                    {
                                        "$ref": "#/components/schemas/requests.UpdateMailingList",
                                        "summary": "list",
                                        "description": "List details"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "List details",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/database.MailingList"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Not Found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Update a mailing list",
                "tags": [
                    "Lists"
                ]
            }
        },
        "/mailing_lists/{id}/recipients": {
            "get": {
                "description": "Get a list of all recipients in a specific mailing list with pagination.",
                "parameters": [
                    {
                        "description": "List ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Start index",
                        "in": "query",
                        "name": "_start",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "End index",
                        "in": "query",
                        "name": "_end",
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/database.Recipient"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "List recipients of a mailing list",
                "tags": [
                    "Lists"
                ]
            },
            "post": {
                "description": "Add a new recipient or link an existing one by email to a mailing list.",
                "parameters": [
                    {
                        "description": "List ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "object"
                                    },
                                    {
                                        "$ref": "#/components/schemas/requests.AddRecipient",
                                        "summary": "recipient",
                                        "description": "Recipient details"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "Recipient details",
                    "required": true
                },
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/database.Recipient"
                                }
                            }
                        },
                        "description": "Created"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Add a recipient to a mailing list",
                "tags": [
                    "Lists"
                ]
            }
        },
        "/mailing_lists/{id}/recipients/{recipientId}": {
            "delete": {
                "description": "Remove a specific recipient from a mailing list by their IDs.",
                "parameters": [
                    {
                        "description": "List ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Recipient ID",
                        "in": "path",
                        "name": "recipientId",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Remove a recipient from a mailing list",
                "tags": [
                    "Lists"
                ]
            }
        },
        "/templates": {
            "get": {
                "description": "Get a list of all email templates with pagination.",
                "parameters": [
                    {
                        "description": "Start index",
                        "in": "query",
                        "name": "_start",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "End index",
                        "in": "query",
                        "name": "_end",
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/database.Template"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "List all email templates",
                "tags": [
                    "Templates"
                ]
            },
            "post": {
                "description": "Create a new email template with the provided name, HTML content, and plain text content.",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "object"
                                    },
                                    {
                                        "$ref": "#/components/schemas/requests.CreateTemplate",
                                        "summary": "template",
                                        "description": "Template details"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "Template details",
                    "required": true
                },
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/database.Template"
                                }
                            }
                        },
                        "description": "Created"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Create a new email template",
                "tags": [
                    "Templates"
                ]
            }
        },
        "/templates/{id}": {
            "delete": {
                "description": "Delete an existing email template by its ID.",
                "parameters": [
                    {
                        "description": "Template ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Not Found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Delete an email template",
                "tags": [
                    "Templates"
                ]
            },
            "get": {
                "description": "Get details of a specific email template by its ID.",
                "parameters": [
                    {
                        "description": "Template ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/database.Template"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Not Found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Get an email template by ID",
                "tags": [
                    "Templates"
                ]
            },
            "patch": {
                "description": "Update an existing email template with the provided ID and details.",
                "parameters": [
                    {
                        "description": "Template ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "object"
                                    },
                                    {
                                        "$ref": "#/components/schemas/requests.UpdateTemplate",
                                        "summary": "template",
                                        "description": "Template details"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "Template details",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/database.Template"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Not Found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/apperrors.AppError"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Update an email template",
                "tags": [
                    "Templates"
                ]
            }
        }
    },
    "openapi": "3.1.0",
    "tags": [
        {
            "description": "Email template management operations",
            "name": "Templates"
        },
        {
            "description": "Mailing list and recipient management operations",
            "name": "Lists"
        }
    ],
    "servers": [
        {
            "url": "skymail-api.yildizskylab.com/v1"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Title:            "Skymail",
	Description:      "This is the API documentation for Skymail.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
