components:
  schemas:
    apperrors.AppError:
      properties:
        code:
          type: string
        message:
          type: string
        params:
          additionalProperties: {}
          type: object
      type: object
    database.MailingList:
      properties:
        created_at:
          type: string
        description:
          type: string
        id:
          type: string
        name:
          type: string
        updated_at:
          type: string
      type: object
    database.Recipient:
      properties:
        created_at:
          type: string
        email:
          type: string
        full_name:
          type: string
        id:
          type: string
        updated_at:
          type: string
      type: object
    database.Template:
      properties:
        created_at:
          type: string
        html_content:
          type: string
        id:
          type: string
        name:
          type: string
        plain_text_content:
          type: string
        updated_at:
          type: string
      type: object
    requests.AddRecipient:
      properties:
        email:
          type: string
        full_name:
          type: string
      required:
      - email
      - full_name
      type: object
    requests.CreateMailingList:
      properties:
        name:
          type: string
      required:
      - name
      type: object
    requests.CreateTemplate:
      properties:
        html_content:
          type: string
        name:
          type: string
        plain_text_content:
          type: string
      required:
      - html_content
      - name
      - plain_text_content
      type: object
    requests.UpdateMailingList:
      properties:
        name:
          type: string
      required:
      - name
      type: object
    requests.UpdateTemplate:
      properties:
        html_content:
          type: string
        name:
          type: string
        plain_text_content:
          type: string
      required:
      - html_content
      - name
      - plain_text_content
      type: object
externalDocs:
  description: ""
  url: ""
info:
  contact:
    email: hello@enesgenc.dev
    name: Enes Genç
    url: https://enesgenc.dev
  description: This is the API documentation for Skymail.
  title: Skymail
  version: "1.0"
openapi: 3.1.0
paths:
  /lists:
    get:
      description: Get a list of all mailing lists.
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/database.MailingList'
                type: array
          description: OK
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apperrors.AppError'
          description: Internal Server Error
      summary: List all mailing lists
      tags:
      - lists
    post:
      description: Create a new mailing list with the provided name.
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - type: object
              - $ref: '#/components/schemas/requests.CreateMailingList'
                description: List details
                summary: list
        description: List details
        required: true
      responses:
        "204":
          description: No Content
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apperrors.AppError'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apperrors.AppError'
          description: Internal Server Error
      summary: Create a new mailing list
      tags:
      - lists
  /lists/{id}:
    delete:
      description: Delete an existing mailing list by its ID.
      parameters:
      - description: List ID
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "204":
          description: No Content
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apperrors.AppError'
          description: Bad Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apperrors.AppError'
          description: Not Found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apperrors.AppError'
          description: Internal Server Error
      summary: Delete a mailing list
      tags:
      - lists
    get:
      description: Get details of a specific mailing list by its ID.
      parameters:
      - description: List ID
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/database.MailingList'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apperrors.AppError'
          description: Bad Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apperrors.AppError'
          description: Not Found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apperrors.AppError'
          description: Internal Server Error
      summary: Get a mailing list by ID
      tags:
      - lists
    put:
      description: Update an existing mailing list with the provided ID and details.
      parameters:
      - description: List ID
        in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - type: object
              - $ref: '#/components/schemas/requests.UpdateMailingList'
                description: List details
                summary: list
        description: List details
        required: true
      responses:
        "204":
          description: No Content
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apperrors.AppError'
          description: Bad Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apperrors.AppError'
          description: Not Found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apperrors.AppError'
          description: Internal Server Error
      summary: Update a mailing list
      tags:
      - lists
  /lists/{id}/recipients:
    get:
      description: Get a list of all recipients in a specific mailing list.
      parameters:
      - description: List ID
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/database.Recipient'
                type: array
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apperrors.AppError'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apperrors.AppError'
          description: Internal Server Error
      summary: List recipients of a mailing list
      tags:
      - lists
    post:
      description: Add a new recipient or link an existing one by email to a mailing
        list.
      parameters:
      - description: List ID
        in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - type: object
              - $ref: '#/components/schemas/requests.AddRecipient'
                description: Recipient details
                summary: recipient
        description: Recipient details
        required: true
      responses:
        "204":
          description: No Content
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apperrors.AppError'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apperrors.AppError'
          description: Internal Server Error
      summary: Add a recipient to a mailing list
      tags:
      - lists
  /lists/{id}/recipients/{recipientId}:
    delete:
      description: Remove a specific recipient from a mailing list by their IDs.
      parameters:
      - description: List ID
        in: path
        name: id
        required: true
        schema:
          type: string
      - description: Recipient ID
        in: path
        name: recipientId
        required: true
        schema:
          type: string
      responses:
        "204":
          description: No Content
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apperrors.AppError'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apperrors.AppError'
          description: Internal Server Error
      summary: Remove a recipient from a mailing list
      tags:
      - lists
  /templates:
    get:
      description: Get a list of all email templates.
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/database.Template'
                type: array
          description: OK
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apperrors.AppError'
          description: Internal Server Error
      summary: List all email templates
      tags:
      - templates
    post:
      description: Create a new email template with the provided name, HTML content,
        and plain text content.
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - type: object
              - $ref: '#/components/schemas/requests.CreateTemplate'
                description: Template details
                summary: template
        description: Template details
        required: true
      responses:
        "204":
          description: No Content
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apperrors.AppError'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apperrors.AppError'
          description: Internal Server Error
      summary: Create a new email template
      tags:
      - templates
  /templates/{id}:
    delete:
      description: Delete an existing email template by its ID.
      parameters:
      - description: Template ID
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "204":
          description: No Content
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apperrors.AppError'
          description: Bad Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apperrors.AppError'
          description: Not Found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apperrors.AppError'
          description: Internal Server Error
      summary: Delete an email template
      tags:
      - templates
    get:
      description: Get details of a specific email template by its ID.
      parameters:
      - description: Template ID
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/database.Template'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apperrors.AppError'
          description: Bad Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apperrors.AppError'
          description: Not Found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apperrors.AppError'
          description: Internal Server Error
      summary: Get an email template by ID
      tags:
      - templates
    put:
      description: Update an existing email template with the provided ID and details.
      parameters:
      - description: Template ID
        in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - type: object
              - $ref: '#/components/schemas/requests.UpdateTemplate'
                description: Template details
                summary: template
        description: Template details
        required: true
      responses:
        "204":
          description: No Content
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apperrors.AppError'
          description: Bad Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apperrors.AppError'
          description: Not Found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apperrors.AppError'
          description: Internal Server Error
      summary: Update an email template
      tags:
      - templates
servers:
- url: skymail-api.yildizskylab.com/v1
